DROP TABLE "BOARD" CASCADE CONSTRAINT;

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER,
	"BOARD_TITLE"	VARCHAR2(255) CONSTRAINT BO_TITLE_NT NOT NULL,
	"BOARD_VIEWS"	NUMBER	DEFAULT 0,
	"BOARD_CREATE_TIME"	DATE DEFAULT SYSDATE,
	"BOARD_MODIFY_TIME"	DATE NULL,
	"BOARD_TYPE"	VARCHAR2(20) CONSTRAINT BO_TYPE_NT NOT NULL,
	"BOARD_COVER_SRC"	VARCHAR2(255) NULL,
	"BOARD_CONTENT"	VARCHAR2(4000) CONSTRAINT BO_CONTENT_NT NOT NULL,
	"FILTER_TYPE"	VARCHAR2(20) CONSTRAINT BO_FI_TYPE_NT NOT NULL,
	"FILTER_AREA"	NUMBER	CONSTRAINT BO_FI_AREA_NT NOT NULL,
	"FILTER_NUM"	NUMBER	NULL,
	"FILTER_DIRECTION"	VARCHAR2(20) NULL,
	"FILTER_PAST"	VARCHAR2(20) NULL,
	"FILTER_LOCAL"	VARCHAR2(255) NULL,
	"FILTER_FAMILY"	VARCHAR2(255) CONSTRAINT BO_FI_FAM_NT NOT NULL,
	"FILTER_PET"	VARCHAR2(20) NULL,
	"FILTER_FAMILY_MEM_CNT"	NUMBER	NULL,
	"FILTER_FIELD"	VARCHAR2(20) NULL,
	"FILTER_WORKER"	VARCHAR2(20) CONSTRAINT BO_FI_WORKER_NT NOT NULL,
	"FILTER_RANGE"	VARCHAR2(20) NULL,
	"FILTER_PERIOD"	NUMBER NULL,
	"FILTER_PERIOD_TYPE" VARCHAR2(20) NULL,
	"FILTER_CONSTRUCTION_PRICE"	NUMBER NULL,
	"FILTER_STYLE_PRICE" NUMBER NULL,
	"FILTER_URL" VARCHAR2(255) NULL,
	"FILTER_COPYRIGHT"	VARCHAR2(20) NULL,
	"MEMBER_NO" NUMBER CONSTRAINT BO_MEMNO_NT  NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_VIEWS" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_CREATE_TIME" IS '생성일';

COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_TIME" IS '수정일';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시글 타입';

COMMENT ON COLUMN "BOARD"."BOARD_COVER_SRC" IS '커버 사진 주소';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."FILTER_TYPE" IS '주거형태';

COMMENT ON COLUMN "BOARD"."FILTER_AREA" IS '평수';

COMMENT ON COLUMN "BOARD"."FILTER_NUM" IS '방개수';

COMMENT ON COLUMN "BOARD"."FILTER_DIRECTION" IS '방향';

COMMENT ON COLUMN "BOARD"."FILTER_PAST" IS '준공연차';

COMMENT ON COLUMN "BOARD"."FILTER_LOCAL" IS '지역';

COMMENT ON COLUMN "BOARD"."FILTER_FAMILY" IS '가족형태';

COMMENT ON COLUMN "BOARD"."FILTER_PET" IS '반려동물';

COMMENT ON COLUMN "BOARD"."FILTER_FAMILY_MEM_CNT" IS '구성원수';

COMMENT ON COLUMN "BOARD"."FILTER_FIELD" IS '작업분야';

COMMENT ON COLUMN "BOARD"."FILTER_WORKER" IS '작업자';

COMMENT ON COLUMN "BOARD"."FILTER_RANGE" IS '시공범위';

COMMENT ON COLUMN "BOARD"."FILTER_PERIOD" IS '기간';

COMMENT ON COLUMN "BOARD"."FILTER_PERIOD_TYPE" IS '주 또는 개월';

COMMENT ON COLUMN "BOARD"."FILTER_CONSTRUCTION_PRICE" IS '공사 예산';

COMMENT ON COLUMN "BOARD"."FILTER_STYLE_PRICE" IS '스타일링예산';

COMMENT ON COLUMN "BOARD"."FILTER_URL" IS '링크';

COMMENT ON COLUMN "BOARD"."FILTER_COPYRIGHT" IS '저작권자';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';
-----------------------------------------------------------------
DROP TABLE "PRODUCT" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT" (
	"PRODUCT_ID" NUMBER,
	"PRODUCT_NAME"	VARCHAR2(100) CONSTRAINT PD_NAME_NT NOT NULL,
	"PRODUCT_PRICE"	VARCHAR(255) NULL,
	"PRODUCT_SALES"	VARCHAR(255) NULL,
	"AMOUNT"	VARCHAR(255) NULL,
	"ARRIVAL_DATE"	VARCHAR(255) NULL,
	"SALE"	NUMBER	NULL,
	"PRODUCT_THUMBNAIL"	VARCHAR2(255) CONSTRAINT PD_THUMB_NT NOT NULL,
	"PRODUCT_IMG"	VARCHAR2(255) CONSTRAINT PD_IMG_NT NOT NULL,
	"PRODUCT_CONTENT"	VARCHAR2(4000) CONSTRAINT PD_CONTENT_NT NOT NULL,
	"PRODUCT_CREATE_TIME" DATE DEFAULT SYSDATE,
	"PRODUCT_MODIFY_TIME" DATE NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT PD_MEMNO_NT  NOT NULL,
	"PRODUCT_DELIVERY_PRICE" NUMBER	DEFAULT 0 NULL,
    "PRODUCT_CATEGORY" NUMBER CONSTRAINT PD_CATEGORY_NT NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_SALES" IS '누적판매량';

COMMENT ON COLUMN "PRODUCT"."AMOUNT" IS '재고수량';

COMMENT ON COLUMN "PRODUCT"."ARRIVAL_DATE" IS '배송완료일';

COMMENT ON COLUMN "PRODUCT"."SALE" IS '할인율';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_THUMBNAIL" IS '썸네일이미지';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_IMG" IS '상품이미지';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_CREATE_TIME" IS '생성일';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_MODIFY_TIME" IS '수정일';

COMMENT ON COLUMN "PRODUCT"."RRODUCT_CATEGORY" IS '카테고리';

COMMENT ON COLUMN "PRODUCT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_DELIVERY_PRICE" IS '배송비';
-------------------------------------------------------------------
DROP TABLE "PRODUCT_OPTIONS" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT_OPTIONS" (
	"PRODUCT_OPTIONS_ID" NUMBER,
	"PRODUCT_OPTIONS_CONTENT" VARCHAR2(4000) CONSTRAINT PDOPT_CONTENT_NT NOT NULL,
	"PRODUCT_OPTIONS_PRICE"	NUMBER CONSTRAINT PDOPT_PRICE_NT NOT NULL,
	"PRODUCT_OPTIONS_STOCK"	NUMBER CONSTRAINT PDOPT_STOCK_NT NOT NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_PDOPT_PDIDNOT NULL
);

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_ID" IS '상품옵션ID';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_CONTENT" IS '옵션내용';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_PRICE" IS '옵션가격';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_STOCK" IS '옵션재고';

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_ID" IS '상품ID';
-------------------------------------------------------------------
DROP TABLE "ORDER" CASCADE CONSTRAINT;

CREATE TABLE "ORDER" (
	"ORDER_ID"	NUMBER,
	"RECIPIENT_NAME"	VARCHAR2(20) CONSTRAINT NT_OR_NAME NOT NULL,
	"RECIPIENT_PHONE"	VARCHAR2(50) CONSTRAINT NT_OR_PHONE NOT NULL,
	"RECIPIENT_EMAIL"	VARCHAR2(255) NULL,
	"RECIPIENT_ADDRESS"	VARCHAR(255) CONSTRAINT NT_OR_RE_ADDRESS NOT NULL,
	"RECIPIENT_POSTCODE" NUMBER CONSTRAINT NT_OR_RE_POSTCODE NOT NULL,
	"ORDER_DATE" DATE DEFAULT SYSDATE,
	"ORDER_AMOUNT" NUMBER CONSTRAINT NT_OR_AMOUNT NOT NULL,
	"PAYMENT_AMOUNT"	NUMBER CONSTRAINT NT_OR_PAYMENT NOT NULL,
	"ORDER_DELIVERY_DATE"	DATE CONSTRAINT NT_OR_DELI_DATE NOT NULL,
	"REQURIEDMENT"	VARCHAR2(255) NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_OR_PDID NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT NT_OR_MEMNO NOT NULL,
	"ORDER_DELIVERY_STATUS"	VARCHAR2(20) CONSTRAINT NT_OR_DELI_STATUS NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_ID" IS '주문번호';

COMMENT ON COLUMN "ORDER"."RECIPIENT_NAME" IS '수령인';

COMMENT ON COLUMN "ORDER"."RECIPIENT_PHONE" IS '수령인전화번호';

COMMENT ON COLUMN "ORDER"."RECIPIENT_EMAIL" IS '수령인이메일';

COMMENT ON COLUMN "ORDER"."RECIPIENT_ADDRESS" IS '수령인주소';

COMMENT ON COLUMN "ORDER"."RECIPIENT_POSTCODE" IS '수령인우편번호';

COMMENT ON COLUMN "ORDER"."ORDER_DATE" IS '주문일자';

COMMENT ON COLUMN "ORDER"."ORDER_AMOUNT" IS '주문수량';

COMMENT ON COLUMN "ORDER"."PAYMENT_AMOUNT" IS '지불금액';

COMMENT ON COLUMN "ORDER"."ORDER_DELIVERY_DATE" IS '배송완료일';

COMMENT ON COLUMN "ORDER"."REQURIEDMENT" IS '요청사항';

COMMENT ON COLUMN "ORDER"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "ORDER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ORDER"."ORDER_DELIVERY_STATUS" IS '배송상태';
-------------------------------------------------------------
DROP TABLE "MEMBER" CASCADE CONSTRAINT;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER,
	"MEMBER_ID"	VARCHAR2(20) CONSTRAINT MEM_ID_NT NOT NULL,
	"MEMBER_PWD"	VARCHAR2(20) CONSTRAINT MEM_PWD_NT NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20) CONSTRAINT MEM_NAME_NT NOT NULL,
	"MEMBER_BIRTH"	DATE NULL,
	"MEMBER_PHONE"	VARCHAR2(20) CONSTRAINT MEM_PHONE_NT NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50) CONSTRAINT MEM_EMAIL_NT NOT NULL,
	"GENDER"	CHAR(1)	CONSTRAINT MEM_GENDER_NT NOT NULL,
	"MEMBER_TYPE"	VARCHAR2(20) CONSTRAINT MEM_TYPE_NT NOT NULL,
	"COMPANY_NAME"	VARCHAR2(255) NULL,
	"REPRESENTATATIVE"	VARCHAR2(20) NULL,
	"COMPANY_PLACE"	VARCHAR2(255) NULL,
	"COMPANY_PHONE"	VARCHAR2(20) NULL,
	"COMPANY_EMAIL"	VARCHAR2(255) NULL,
	"REG_NUM"	VARCHAR2(20) NULL,
    "MEMBER_STATUS" CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '회원성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_TYPE" IS '회원타입';

COMMENT ON COLUMN "MEMBER"."COMPANY_NAME" IS '상호';

COMMENT ON COLUMN "MEMBER"."REPRESENTATATIVE" IS '대표자';

COMMENT ON COLUMN "MEMBER"."COMPANY_PLACE" IS '사업장소재지';

COMMENT ON COLUMN "MEMBER"."COMPANY_PHONE" IS '회사전화번호';

COMMENT ON COLUMN "MEMBER"."COMPANY_EMAIL" IS '회사이메일';

COMMENT ON COLUMN "MEMBER"."REG_NUM" IS '사업자등록번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_STATUS" IS '회원 상태';
-----------------------------------------------------------
DROP TABLE "PRODUCT_BASKET" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT_BASKET" (
	"PRODUCT_ID" NUMBER CONSTRAINT NT_PDBAS_PDID NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT NT_PDBAS_MEMNO NOT NULL,
	"QUANTITY"	NUMBER CONSTRAINT NT_PDBAS_QUAN NOT NULL
);

COMMENT ON COLUMN "PRODUCT_BASKET"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "PRODUCT_BASKET"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PRODUCT_BASKET"."QUANTITY" IS '수량';
------------------------------------------------------------------
DROP TABLE "QNA";

CREATE TABLE "QNA" (
	"QNA_ID" NUMBER,
	"QNA_ISSUE_DATE" DATE DEFAULT SYSDATE,
	"QNA_CONTENT" VARCHAR2(4000) NULL,
	"QNA_TYPE"	CHAR(1)	DEFAULT 'Q',
	"QNA_CONFIDENTIAL"	CHAR(1)	DEFAULT 'N',
	"PRODUCT_ID" NUMBER CONSTRAINT NT_QNA_PDID NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT NT_QNA_MEMNO NOT NULL
);

COMMENT ON COLUMN "QNA"."QNA_ID" IS '질답ID';

COMMENT ON COLUMN "QNA"."QNA_ISSUE_DATE" IS '작성일';

COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '내용';

COMMENT ON COLUMN "QNA"."QNA_TYPE" IS '질답타입';

COMMENT ON COLUMN "QNA"."QNA_CONFIDENTIAL" IS '비밀글여부';

COMMENT ON COLUMN "QNA"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "QNA"."MEMBER_NO" IS '회원번호';
---------------------------------------------------------------
DROP TABLE "BOARD_MEDIA" CASCADE CONSTRAINT;

CREATE TABLE "BOARD_MEDIA" (
	"MEDIA_ID"	NUMBER,
	"MEDIA_TYPE" NUMBER CONSTRAINT NT_BOMED_TYPE NOT NULL,
	"MEDIA_SRC"	VARCHAR2(255) CONSTRAINT NT_BOMED_SRC NOT NULL,
	"BOARD_ID"	NUMBER CONSTRAINT NT_BOMED_BOID	NOT NULL
);

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_TYPE" IS '사진 동영상';

COMMENT ON COLUMN "BOARD_MEDIA"."MEDIA_SRC" IS '미디어 주소';

COMMENT ON COLUMN "BOARD_MEDIA"."BOARD_ID" IS '게시글ID';
------------------------------------------------------------------
DROP TABLE "REPLY" CASCADE CONSTRAINT;

CREATE TABLE "REPLY" (
	"REPLY_ID"	NUMBER,
	"REPLY_TEXT" VARCHAR2(4000) CONSTRAINT REP_TEXT_NT NOT NULL,
	"REPLY_CREATE_DATE"	DATE DEFAULT SYSDATE,
	"REPLY_MODIFT_DATE"	DATE NULL,
	"BOARD_ID"	NUMBER CONSTRAINT NT_REPLY_BOID NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT NT_REPLY_MEMNO NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_ID" IS '댓글ID';

COMMENT ON COLUMN "REPLY"."REPLY_TEXT" IS '댓글 텍스트';

COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '생성일';

COMMENT ON COLUMN "REPLY"."REPLY_MODIFT_DATE" IS '수정일';

COMMENT ON COLUMN "REPLY"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호';
---------------------------------------------------------------
DROP TABLE "REVIEW" CASCADE CONSTRAINT;

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	NUMBER,
	"RATING"	NUMBER	CONSTRAINT NT_REV_RATING NOT NULL,
	"REVIEW_IMG"	VARCHAR2(255) CONSTRAINT NT_REV_IMG NOT NULL,
	"REVIEW_DETAIL"	VARCHAR2(4000) CONSTRAINT NT_REV_DETAIL NOT NULL,
	"HELPFUL"	VARCHAR(255) NULL,
	"REVIEW_CREATE_DAY"	DATE DEFAULT SYSDATE,
	"REVIEW_MODIFT_DAY"	DATE DEFAULT SYSDATE NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_REV_PDID NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT NT_REV_MEMNO NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰ID';

COMMENT ON COLUMN "REVIEW"."RATING" IS '별점';

COMMENT ON COLUMN "REVIEW"."REVIEW_IMG" IS '리뷰이미지';

COMMENT ON COLUMN "REVIEW"."REVIEW_DETAIL" IS '리뷰내용';

COMMENT ON COLUMN "REVIEW"."HELPFUL" IS '도움이돼요';

COMMENT ON COLUMN "REVIEW"."REVIEW_CREATE_DAY" IS '생성일';

COMMENT ON COLUMN "REVIEW"."REVIEW_MODIFT_DAY" IS '수정일';

COMMENT ON COLUMN "REVIEW"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "REVIEW"."MEMBER_NO" IS '회원번호';
--------------------------------------------------------------------
DROP TABLE "TAG" CASCADE CONSTRAINT;

CREATE TABLE "TAG" (
	"MEDIA_ID"	NUMBER CONSTRAINT NT_TAG_MEDID NOT NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_TAG_PDOD  NOT NULL,
	"TAG_X"	NUMBER CONSTRAINT "NT_TAG_X" NOT NULL,
	"TAG_Y"	NUMBER CONSTRAINT "NT_TAG_Y" NOT NULL
);

COMMENT ON COLUMN "TAG"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "TAG"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "TAG"."TAG_X" IS '태그  X  좌표';

COMMENT ON COLUMN "TAG"."TAG_Y" IS '태그 Y 좌표';
------------------------------------------------------------
DROP TABLE "SCRAP" CASCADE CONSTRAINT ;

CREATE TABLE "SCRAP" (
	"SCRAP_ID"	NUMBER,
	"SCRAP_TYPE" NUMBER CONSTRAINT "NT_SCRAP_TYPE" NOT NULL,
	"MEMBER_NO"	NUMBER CONSTRAINT "NT_SCRAP_MEMNO" NOT NULL,
	"BOARD_ID"	NUMBER,
	"MEDIA_ID"	NUMBER,
	"PRODUCT_ID" NUMBER,
	"SCRAP_CREATE_TIME"	DATE DEFAULT SYSDATE,
	"SCRAP_MODIFY_TIME"	DATE DEFAULT SYSDATE NULL
);

COMMENT ON COLUMN "SCRAP"."SCRAP_ID" IS '스크랩ID';

COMMENT ON COLUMN "SCRAP"."SCRAP_TYPE" IS '스크랩타입';

COMMENT ON COLUMN "SCRAP"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "SCRAP"."BOARD_ID" IS '게시글ID';

COMMENT ON COLUMN "SCRAP"."MEDIA_ID" IS '미디어ID';

COMMENT ON COLUMN "SCRAP"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "SCRAP"."SCRAP_CREATE_TIME" IS '스크랩생성일';

COMMENT ON COLUMN "SCRAP"."SCRAP_MODIFY_TIME" IS '스크랩수정일';
--==============================================================
-- 제약 조건 설정 부분(외래키 제외)
-- 게시글
ALTER TABLE "BOARD"
    ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (BOARD_ID);
    
-- 상품
ALTER TABLE "PRODUCT" 
    ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
    ADD CONSTRAINT UQ_PD_NAME UNIQUE (PRODUCT_NAME);
    
-- PRODUCT_OPTIONS
ALTER TABLE "PRODUCT_OPTIONS" ADD CONSTRAINT "PK_PRODUCT_OPTIONS" PRIMARY KEY ("PRODUCT_OPTIONS_ID");

-- ORDER
ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY ("ORDER_ID");

-- MEMBER
ALTER TABLE "MEMBER" 
    ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (MEMBER_NO)
    ADD CONSTRAINT "UQ_MEMBER_ID" UNIQUE (MEMBER_ID)
    ADD CONSTRAINT "UQ_MEMBER_EMAIL" UNIQUE (MEMBER_EMAIL)
    ADD CONSTRAINT "UQ_MEMBER_PHONE" UNIQUE (MEMBER_PHONE)
    ADD CONSTRAINT "CK_MEM_GENDER" CHECK (GENDER IN ('M', 'F'))
    ADD CONSTRAINT "CK_MEM_STATUS" CHECK (MEMBER_STATUS IN ('Y', 'N'));

-- PRODUCT_BASKET
ALTER TABLE "PRODUCT_BASKET" ADD CONSTRAINT "PK_PRODUCT_BASKET" PRIMARY KEY ("PRODUCT_ID", "MEMBER_NO");

-- QNA
ALTER TABLE "QNA"
    ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("QNA_ID")
    ADD CONSTRAINT CK_QNA_TYPE CHECK (QNA_TYPE IN ('Q', 'A'))
    ADD CONSTRAINT CK_QNA_CONFIDENTIAL CHECK (QNA_TYPE IN ('N', 'Y'));

-- BOARD_MEDIA
ALTER TABLE "BOARD_MEDIA"
    ADD CONSTRAINT "PK_BOARD_MEDIA" PRIMARY KEY ("MEDIA_ID")
    ADD CONSTRAINT CK_MEDIA_TYPE CHECK (MEDIA_TYPE IN (1, 2));

-- REPLY
ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_ID");
    
-- REVIEW
ALTER TABLE "REVIEW"
    ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_ID")
    ADD CONSTRAINT CK_REV_RATING CHECK (RATING IN (1, 2, 3, 4, 5));

-- TAG
ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY ("MEDIA_ID","PRODUCT_ID");

-- SCRAP
ALTER TABLE "SCRAP" ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY ("SCRAP_ID");

--외래키 추가 구문
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE PRODUCT ADD CONSTRAINT "FK_MEMBER_TO_PRODUCT" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "PRODUCT_OPTIONS" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_OPTIONS" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE "ORDER" 
    ADD CONSTRAINT "FK_PRODUCT_TO_ORDER" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBER_TO_ORDER" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "PRODUCT_BASKET" 
    ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_BASKET" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBER_TO_PRODUCT_BASKET" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "QNA" 
    ADD CONSTRAINT "FK_PRODUCT_TO_QNA" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBER_TO_QNA" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "BOARD_MEDIA" ADD CONSTRAINT "FK_BOARD_TO_BOARD_MEDIA" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID");

ALTER TABLE "REPLY" 
    ADD CONSTRAINT "FK_BOARD_TO_REPLY" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID")
    ADD CONSTRAINT "FK_MEMBER_TO_REPLY" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "REVIEW" 
    ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBER_TO_REVIEW" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "TAG" 
    ADD CONSTRAINT "FK_BOARD_MEDIA_TO_TAG" FOREIGN KEY ("MEDIA_ID") REFERENCES "BOARD_MEDIA" ("MEDIA_ID")
    ADD CONSTRAINT "FK_PRODUCT_TO_TAG" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_SCRAP" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_BOARD_TO_SCRAP" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_BOARD_MEDIA_TO_SCRAP" FOREIGN KEY ("MEDIA_ID") REFERENCES "BOARD_MEDIA" ("MEDIA_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_PRODUCT_TO_SCRAP" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");
-- ====================================================================================================================
-- 시퀀스 생성 구문
-- =========================================================================================================================
-- 트리거 생성 구문

