----------삭제-------------
--접속유저의 모든 테이블 및 제약조건 삭제
SET DEFINE OFF;

BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/

--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/

--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
--========================================= 테이블 생성 ============================
-- BOARD --
CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER,
	"BOARD_TITLE"	VARCHAR2(255) CONSTRAINT NT_BOD_TITLE NOT NULL,
	"BOARD_VIEWS"	NUMBER	DEFAULT 0,
	"BOARD_CREATE_TIME"	DATE DEFAULT SYSDATE,
	"BOARD_MODIFY_TIME"	DATE NULL,
    BOARD_INTRODUCTION VARCHAR2(4000) CONSTRAINT NT_BOD_INTRO NOT NULL,
	"BOARD_DESCRIPTION"	VARCHAR2(4000) CONSTRAINT NT_BOD_DES NOT NULL,
	"FILTER_TYPE"	VARCHAR2(20) CONSTRAINT NT_BOD_FI_TYPE NOT NULL,
	"FILTER_AREA"	NUMBER	CONSTRAINT NT_BOD_FI_AREA NOT NULL,
	"FILTER_NUM"	NUMBER,
	"FILTER_DIRECTION"	VARCHAR2(20) NULL,
	"FILTER_PAST"	VARCHAR2(20) NULL,
	"FILTER_LOCAL"	VARCHAR2(255) NULL,
	"FILTER_FAMILY"	VARCHAR2(255) CONSTRAINT NT_BOD_FI_FAM NOT NULL,
	"FILTER_PET"	VARCHAR2(20) NULL,
	"FILTER_FAMILY_MEM_CNT"	NUMBER,
	"FILTER_FIELD"	VARCHAR2(20) CONSTRAINT NT_BOD_FI_FIELD NOT NULL,
	"FILTER_WORKER"	VARCHAR2(20) CONSTRAINT NT_BOD_FI_WORKER NOT NULL,
	"FILTER_RANGE"	VARCHAR2(20) NULL,
	"FILTER_PERIOD"	NUMBER,
	"FILTER_PERIOD_TYPE" VARCHAR2(20),
	"FILTER_CONSTRUCTION_PRICE"	NUMBER,
	"FILTER_STYLE_PRICE" NUMBER NULL,
	"FILTER_URL" VARCHAR2(255) NULL,
	"FILTER_COPYRIGHT"	VARCHAR2(20) NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT NT_BOD_MEMNO NOT NULL,
    BOARD_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_VIEWS" IS '조회수';
COMMENT ON COLUMN "BOARD"."BOARD_CREATE_TIME" IS '생성일';
COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_TIME" IS '수정일';
COMMENT ON COLUMN "BOARD"."BOARD_INTRODUCTION" IS '소개글';
COMMENT ON COLUMN "BOARD"."BOARD_DESCRIPTION" IS '묘사글';
COMMENT ON COLUMN "BOARD"."FILTER_TYPE" IS '주거형태';
COMMENT ON COLUMN "BOARD"."FILTER_AREA" IS '평수';
COMMENT ON COLUMN "BOARD"."FILTER_NUM" IS '방개수';
COMMENT ON COLUMN "BOARD"."FILTER_DIRECTION" IS '방향';
COMMENT ON COLUMN "BOARD"."FILTER_PAST" IS '준공연차';
COMMENT ON COLUMN "BOARD"."FILTER_LOCAL" IS '지역';
COMMENT ON COLUMN "BOARD"."FILTER_FAMILY" IS '가족형태';
COMMENT ON COLUMN "BOARD"."FILTER_PET" IS '반려동물';
COMMENT ON COLUMN "BOARD"."FILTER_FAMILY_MEM_CNT" IS '구성원수';
COMMENT ON COLUMN "BOARD"."FILTER_FIELD" IS '작업분야';
COMMENT ON COLUMN "BOARD"."FILTER_WORKER" IS '작업자';
COMMENT ON COLUMN "BOARD"."FILTER_RANGE" IS '시공범위';
COMMENT ON COLUMN "BOARD"."FILTER_PERIOD" IS '기간';
COMMENT ON COLUMN "BOARD"."FILTER_PERIOD_TYPE" IS '주 또는 개월';
COMMENT ON COLUMN "BOARD"."FILTER_CONSTRUCTION_PRICE" IS '공사 예산';
COMMENT ON COLUMN "BOARD"."FILTER_STYLE_PRICE" IS '스타일링예산';
COMMENT ON COLUMN "BOARD"."FILTER_URL" IS '링크';
COMMENT ON COLUMN "BOARD"."FILTER_COPYRIGHT" IS '저작권자';
COMMENT ON COLUMN "BOARD"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN BOARD.BOARD_STATUS IS '게시글 상태(현존 여부)';
-----------------------------------------------------------------
-- PRODUCT --
CREATE TABLE "PRODUCT" (
	"PRODUCT_ID" NUMBER,
	"PRODUCT_NAME"	VARCHAR2(255) CONSTRAINT NT_PD_NAME NOT NULL,
	"PRODUCT_PRICE"	NUMBER CONSTRAINT NT_PD_PRICE NOT NULL,
	"PRODUCT_SALES"	NUMBER DEFAULT 0,
	"STOCK"	NUMBER DEFAULT 0 CONSTRAINT NT_PD_STOCK NOT NULL,
	"DELIVERY_DATE"	NUMBER DEFAULT 1,
	"SALE"	NUMBER DEFAULT 0,
	"PRODUCT_CONTENT"	VARCHAR2(4000) CONSTRAINT NT_PD_CONTENT NOT NULL,
	"PRODUCT_CREATE_TIME" DATE DEFAULT SYSDATE,
	"PRODUCT_MODIFY_TIME" DATE NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT NT_PD_MEMNO NOT NULL,
	"PRODUCT_DELIVERY_PRICE" NUMBER	DEFAULT 0 NULL,
    "PRODUCT_CATEGORY" NUMBER CONSTRAINT NT_PD_CATEGORY NOT NULL,
    PRODUCT_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품명';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_PRICE" IS '가격';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_SALES" IS '누적판매량';
COMMENT ON COLUMN "PRODUCT"."STOCK" IS '재고수량';
COMMENT ON COLUMN "PRODUCT"."DELIVERY_DATE" IS '배송소요일';
COMMENT ON COLUMN "PRODUCT"."SALE" IS '할인율';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CREATE_TIME" IS '생성일';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_MODIFY_TIME" IS '수정일';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CATEGORY" IS '카테고리(가구(1) / 패브릭(2) / 생활용품(3) / 가전 및 디지털(4) / 기타(5))';
COMMENT ON COLUMN "PRODUCT"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_DELIVERY_PRICE" IS '배송비';
--------------------------------------------------------------------
-- PRODUCT_OPTIONS --
CREATE TABLE "PRODUCT_OPTIONS" (
	PRODUCT_OPTIONS_ID NUMBER,
    PDOPT_PRODUCT_ID NUMBER CONSTRAINT NT_PDOPT_PDIDNOT NULL,
	PRODUCT_OPTIONS_CONTENT VARCHAR2(4000),
    PRODUCT_OPTIONS_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN PRODUCT_OPTIONS.PRODUCT_OPTIONS_ID IS '상품 옵션 ID';
COMMENT ON COLUMN PRODUCT_OPTIONS.PDOPT_PRODUCT_ID IS '상품 ID';
COMMENT ON COLUMN PRODUCT_OPTIONS.PRODUCT_OPTIONS_CONTENT IS '상품 세부 내용';
COMMENT ON COLUMN PRODUCT_OPTIONS.PRODUCT_OPTIONS_STATUS IS '상품 옵션 현존 상태';

-- OPTIONS_CATEGORT : 옵션명
CREATE TABLE OPTIONS_CATEGORY(
    OPTIONS_NO NUMBER,
    OPTIONS_PDOPT_ID NUMBER CONSTRAINT NT_OPTCG_PDOPTID NOT NULL,
    OPTIONS_CATEGORY VARCHAR2(100) CONSTRAINT NT_OPTCG_CATEGORY NOT NULL
);
COMMENT ON COLUMN OPTIONS_CATEGORY.OPTIONS_NO IS '상품 옵션명 번호';
COMMENT ON COLUMN OPTIONS_CATEGORY.OPTIONS_PDOPT_ID IS '상품 옵션 번호';
COMMENT ON COLUMN OPTIONS_CATEGORY.OPTIONS_CATEGORY IS '상품 옵션명';

-- OPTIONS_NAME : 옵션값
CREATE TABLE OPTIONS_NAME(
    OPTIONS_NAME_NO NUMBER,
    OPTIONS_NAME_OPT_NO NUMBER CONSTRAINT NT_OPTNAME_OPT_NO NOT NULL,
    OPTIONS_NAME VARCHAR2(100) CONSTRAINT NT_OPTNAME_NAME NOT NULL,
    OPTIONS_PRICE NUMBER DEFAULT 0 CONSTRAINT NT_OPTNAME_PRICE NOT NULL,
    OPTIONS_STOCK NUMBER DEFAULT 0 CONSTRAINT NT_OPTNAME_STOCK NOT NULL
);
COMMENT ON COLUMN OPTIONS_NAME.OPTIONS_NAME_NO IS '상품 옵션값 번호';
COMMENT ON COLUMN OPTIONS_NAME.OPTIONS_NAME_OPT_NO IS '상품 옵션명 번호';
COMMENT ON COLUMN OPTIONS_NAME.OPTIONS_NAME IS '상품 옵션값';
COMMENT ON COLUMN OPTIONS_NAME.OPTIONS_PRICE IS '상품 옵션값 추가 금액';
COMMENT ON COLUMN OPTIONS_NAME.OPTIONS_STOCK IS '상품 옵션값 재고';
-------------------------------------------------------------------
-- ORDERS --
CREATE TABLE "ORDERS" (
	ORDERS_ID	NUMBER,
    MEMBERS_NO	NUMBER CONSTRAINT NT_ORD_MEMNO NOT NULL,
	RECIPIENT_NAME	VARCHAR2(20) CONSTRAINT NT_ORD_NAME NOT NULL,
	RECIPIENT_PHONE	VARCHAR2(50) CONSTRAINT NT_ORD_PHONE NOT NULL,
	RECIPIENT_EMAIL	VARCHAR2(255) NULL,
	"RECIPIENT_ADDRESS"	VARCHAR(255) CONSTRAINT NT_ORD_RE_ADDRESS NOT NULL,
	"RECIPIENT_POSTCODE" NUMBER CONSTRAINT NT_ORD_RE_POSTCODE NOT NULL,
	"ORDERS_DATE" DATE DEFAULT SYSDATE,
	TOTAL_PRICE	NUMBER CONSTRAINT NT_ORD_TOTALPRICE NOT NULL,
	"ARRIVAL_DATE" DATE DEFAULT SYSDATE,
	"REQURIEDMENT"	VARCHAR2(255) NULL,
	"ORDERS_DELIVERY_STATUS"	VARCHAR2(20) CONSTRAINT NT_ORD_DELI_STATUS NOT NULL,
    ORDERS_STATUS CHAR(1) DEFAULT 'Y'
);
-- 주문 취소 ???? -> 트리거 걸려있기 때문에 까다로워짐
COMMENT ON COLUMN "ORDERS"."ORDERS_ID" IS '주문번호';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_NAME" IS '수령인';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_PHONE" IS '수령인전화번호';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_EMAIL" IS '수령인이메일';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_ADDRESS" IS '수령인주소';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_POSTCODE" IS '수령인우편번호';
COMMENT ON COLUMN "ORDERS"."ORDERS_DATE" IS '주문일자';
COMMENT ON COLUMN "ORDERS"."TOTAL_PRICE" IS '지불금액';
COMMENT ON COLUMN "ORDERS"."ARRIVAL_DATE" IS '배송완료일';
COMMENT ON COLUMN "ORDERS"."REQURIEDMENT" IS '요청사항';
COMMENT ON COLUMN "ORDERS"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "ORDERS"."ORDERS_DELIVERY_STATUS" IS '배송상태';
COMMENT ON COLUMN ORDERS.ORDERS_STATUS IS '주문 유효 여부';
--------------------------------------------------------------
-- 주문-상품 테이블
CREATE TABLE ORDERS_PRODUCT (
    ORDERS_ID NUMBER CONSTRAINT NT_ORDPD_ORDID NOT NULL,
    PRODUCT_ID NUMBER CONSTRAINT NT_ORDPD_PDID NOT NULL,
    OPTIONS_NAME_NO NUMBER CONSTRAINT NT_ORDPD_OPTNAME NOT NULL,
    AMOUNT NUMBER CONSTRAINT NT_ORDPD_AMOUNT NOT NULL
);

COMMENT ON COLUMN ORDERS_PRODUCT.ORDERS_ID IS '주문ID';
COMMENT ON COLUMN ORDERS_PRODUCT.PRODUCT_ID IS '상품ID';
COMMENT ON COLUMN ORDERS_PRODUCT.OPTIONS_NAME_NO IS '옵션명ID';
COMMENT ON COLUMN ORDERS_PRODUCT.AMOUNT IS '개별 주문 수량';


-------------------------------------------------------------
-- MEMBERS --
CREATE TABLE "MEMBERS" (
	"MEMBERS_NO"	NUMBER,
	"MEMBERS_ID"	VARCHAR2(20) CONSTRAINT NT_MEM_ID NOT NULL,
	"MEMBERS_PWD"	VARCHAR2(20) CONSTRAINT NT_MEM_PWD NOT NULL,
	"MEMBERS_NAME"	VARCHAR2(20),
	"MEMBERS_BIRTH"	DATE NULL,
	"MEMBERS_PHONE"	VARCHAR2(20),
	"MEMBERS_EMAIL"	VARCHAR2(50),
	"GENDER" VARCHAR2(20) NULL,
	"MEMBERS_TYPE"	NUMBER DEFAULT 1,
	"COMPANY_NAME"	VARCHAR2(255) NULL,
	"REPRESENTATATIVE"	VARCHAR2(20) NULL,
	"COMPANY_PLACE"	VARCHAR2(255) NULL,
	"COMPANY_PHONE"	VARCHAR2(20) NULL,
	"COMPANY_EMAIL"	VARCHAR2(255) NULL,
	"REG_NUM"	VARCHAR2(20) NULL,
    MEMBERS_ENROLL_TIME DATE DEFAULT SYSDATE,
    MEMBERS_MODIFY_TIME DATE NULL,
    MEMBERS_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "MEMBERS"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_ID" IS '회원아이디';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_PWD" IS '회원비밀번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_NAME" IS '회원닉네임';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_BIRTH" IS '회원생년월일';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_PHONE" IS '회원전화번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_EMAIL" IS '회원이메일';
COMMENT ON COLUMN "MEMBERS"."GENDER" IS '회원성별';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_TYPE" IS '회원타입';
COMMENT ON COLUMN "MEMBERS"."COMPANY_NAME" IS '상호';
COMMENT ON COLUMN "MEMBERS"."REPRESENTATATIVE" IS '대표자';
COMMENT ON COLUMN "MEMBERS"."COMPANY_PLACE" IS '사업장소재지';
COMMENT ON COLUMN "MEMBERS"."COMPANY_PHONE" IS '회사전화번호';
COMMENT ON COLUMN "MEMBERS"."COMPANY_EMAIL" IS '회사이메일';
COMMENT ON COLUMN "MEMBERS"."REG_NUM" IS '사업자등록번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_ENROLL_TIME" IS '회원 가입 일시';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_MODIFY_TIME" IS '회원 정보 수정 일시';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_STATUS" IS '회원 상태';
-----------------------------------------------------------
-- PRODUCT_CART --
CREATE TABLE "PRODUCT_CART" (
	"PRODUCT_ID" NUMBER CONSTRAINT NT_PDC_PDID NOT NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT NT_PDC_MEMNO NOT NULL,
	CART_AMOUNT	NUMBER CONSTRAINT NT_PDC_AMOUNT NOT NULL
);
-- 삭제 시 DELETE
COMMENT ON COLUMN "PRODUCT_CART"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "PRODUCT_CART"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "PRODUCT_CART"."CART_AMOUNT" IS '수량';
------------------------------------------------------------------
-- QNA --
CREATE TABLE "QNA" (
	"QNA_ID" NUMBER,
	"QNA_ISSUE_DATE" DATE DEFAULT SYSDATE,
	"QNA_CONTENT" VARCHAR2(4000) NULL,
	"QNA_TYPE"	CHAR(1)	DEFAULT 'Q',
	"QNA_CONFIDENTIAL"	CHAR(1)	DEFAULT 'N',
	"PRODUCT_ID" NUMBER CONSTRAINT NT_QNA_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_QNA_MEMNO NOT NULL,
    QNA_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "QNA"."QNA_ID" IS '질답ID';
COMMENT ON COLUMN "QNA"."QNA_ISSUE_DATE" IS '작성일';
COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '내용';
COMMENT ON COLUMN "QNA"."QNA_TYPE" IS '질답타입';
COMMENT ON COLUMN "QNA"."QNA_CONFIDENTIAL" IS '비밀글여부';
COMMENT ON COLUMN "QNA"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "QNA"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN QNA.QNA_STATUS IS '질답 상태';
---------------------------------------------------------------
-- MEDIA --
CREATE TABLE MEDIA (
	MEDIA_ID NUMBER,
    BOARD_ID NUMBER,
    MEMBERS_NO NUMBER,
    PRODUCT_ID NUMBER,
    MEDIA_TYPE NUMBER CONSTRAINT NT_MED_TYPE NOT NULL,
	ORIGIN_NAME VARCHAR2(255) CONSTRAINT NT_MED_ORIGIN NOT NULL,
    CHANGE_NAME VARCHAR2(255) CONSTRAINT NT_MED_CHANGE NOT NULL,
    FILE_PATH	VARCHAR2(1000) CONSTRAINT NT_MED_FILE_PATH NOT NULL,
    FILE_LEVEL NUMBER DEFAULT '2' CONSTRAINT NT_MED_LEVEL NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE,
    MEDIA_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "MEDIA"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "MEDIA"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "MEDIA".MEMBERS_NO IS '회원 번호';
COMMENT ON COLUMN "MEDIA".PRODUCT_ID IS '상품 번호';
COMMENT ON COLUMN "MEDIA"."MEDIA_TYPE" IS '사진(1) / 동영상(2)';
COMMENT ON COLUMN "MEDIA".ORIGIN_NAME IS '원본명';
COMMENT ON COLUMN "MEDIA".CHANGE_NAME IS '수정명';
COMMENT ON COLUMN "MEDIA".FILE_PATH IS '미디어 저장 경로';
COMMENT ON COLUMN "MEDIA".FILE_LEVEL IS '썸네일(1)/개별이미지(2)/프로필사진(3)';
COMMENT ON COLUMN MEDIA.MEDIA_STATUS IS '미디어 상태';
COMMENT ON COLUMN MEDIA.UPLOAD_DATE IS '미디어 게시일';
------------------------------------------------------------------
-- REPLY --
CREATE TABLE "REPLY" (
	"REPLY_ID"	NUMBER,
	REPLY_CONTENT VARCHAR2(4000) CONSTRAINT NT_REP_CONTENT NOT NULL,
	"REPLY_CREATE_DATE"	DATE DEFAULT SYSDATE,
	"REPLY_MODIFY_DATE"	DATE NULL,
	"BOARD_ID"	NUMBER CONSTRAINT NT_REP_BODID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_REP_MEMNO NOT NULL,
    REPLY_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "REPLY"."REPLY_ID" IS '댓글ID';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 텍스트';
COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "REPLY"."REPLY_MODIFY_DATE" IS '수정일';
COMMENT ON COLUMN "REPLY"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "REPLY"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN REPLY.REPLY_STATUS IS '댓글 상태';
---------------------------------------------------------------
-- REVIEW --
CREATE TABLE "REVIEW" (
	"REVIEW_ID"	NUMBER,
	"RATING"	NUMBER	CONSTRAINT NT_REV_RATING NOT NULL,
	"REVIEW_IMG"	VARCHAR2(1000),
	REVIEW_CONTENT	VARCHAR2(4000) CONSTRAINT NT_REV_CONTENT NOT NULL,
	"HELPFUL"	VARCHAR(255) NULL,
	"REVIEW_CREATE_DATE" DATE DEFAULT SYSDATE,
	"REVIEW_MODIFY_DATE" DATE DEFAULT SYSDATE NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_REV_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_REV_MEMNO NOT NULL,
    REVIEW_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰ID';
COMMENT ON COLUMN "REVIEW"."RATING" IS '별점';
COMMENT ON COLUMN "REVIEW"."REVIEW_IMG" IS '리뷰이미지';
COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '리뷰내용';
COMMENT ON COLUMN "REVIEW"."HELPFUL" IS '도움이돼요';
COMMENT ON COLUMN "REVIEW"."REVIEW_CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "REVIEW"."REVIEW_MODIFY_DATE" IS '수정일';
COMMENT ON COLUMN "REVIEW"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "REVIEW"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN REVIEW.REVIEW_STATUS IS '리뷰 상태';
--------------------------------------------------------------------
-- TAG -- 
CREATE TABLE "TAG" (
	"MEDIA_ID"	NUMBER CONSTRAINT NT_TAG_MEDID NOT NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_TAG_PDOD  NOT NULL,
	"TAG_X"	NUMBER CONSTRAINT "NT_TAG_X" NOT NULL,
	"TAG_Y"	NUMBER CONSTRAINT "NT_TAG_Y" NOT NULL
);
-- 삭제 시 DELETE
COMMENT ON COLUMN "TAG"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "TAG"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "TAG"."TAG_X" IS '태그  X  좌표';
COMMENT ON COLUMN "TAG"."TAG_Y" IS '태그 Y 좌표';
------------------------------------------------------------
-- SCRAP --
CREATE TABLE "SCRAP" (
	"SCRAP_ID"	NUMBER,
	"SCRAP_TYPE" NUMBER CONSTRAINT "NT_SCRAP_TYPE" NOT NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT "NT_SCRAP_MEMNO" NOT NULL,
	"BOARD_ID"	NUMBER,
	"MEDIA_ID"	NUMBER,
	"PRODUCT_ID" NUMBER,
	"SCRAP_CREATE_TIME"	DATE DEFAULT SYSDATE,
    SCRAP_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "SCRAP"."SCRAP_ID" IS '스크랩ID';
COMMENT ON COLUMN "SCRAP"."SCRAP_TYPE" IS '스크랩타입(상품(1)/사진(2)/집들이(3))';
COMMENT ON COLUMN "SCRAP"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "SCRAP"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "SCRAP"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "SCRAP"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "SCRAP"."SCRAP_CREATE_TIME" IS '스크랩생성일';
COMMENT ON COLUMN SCRAP.SCRAP_STATUS IS '스크랩 유효 여부';
--================================ 제약 조건 ==============================
--------------------------- 제약조건(외래키제외)
-- 게시글
ALTER TABLE "BOARD"
    ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (BOARD_ID)
    ADD CONSTRAINT CK_BOD_STATUS CHECK (BOARD_STATUS IN ('Y', 'N'));
-- 상품
ALTER TABLE "PRODUCT" 
    ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
    ADD CONSTRAINT UQ_PD_NAME UNIQUE (PRODUCT_NAME)
    ADD CONSTRAINT CK_PD_STOCK CHECK (STOCK > 0)
    ADD CONSTRAINT CK_PD_STATUS CHECK (PRODUCT_STATUS IN ('Y', 'N'));
    -- 트리거로 인해 STOCK 이 0 아래로 내려가는 것을 방지하기 위한 제약 조건 설정

-- PRODUCT_OPTIONS
ALTER TABLE "PRODUCT_OPTIONS"
    ADD CONSTRAINT "PK_PRODUCT_OPTIONS" PRIMARY KEY ("PRODUCT_OPTIONS_ID")
    ADD CONSTRAINT CK_PDOPT_STATUS CHECK (PRODUCT_OPTIONS_STATUS IN ('Y', 'N'));

-- OPTIONS_CATEGORY
ALTER TABLE OPTIONS_CATEGORY
    ADD CONSTRAINT PK_OPTIONS_CATEGORY PRIMARY KEY ("OPTIONS_NO");

-- OPTIONS_NAME
ALTER TABLE OPTIONS_NAME
    ADD CONSTRAINT PK_OPTIONS_NAME PRIMARY KEY ("OPTIONS_NAME_NO");

-- ORDERS
ALTER TABLE "ORDERS" 
    ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDERS_ID")
    ADD CONSTRAINT CK_ORD_STATUS CHECK (ORDERS_STATUS IN ('Y', 'N'));

-- ORDER_PRODUCT
ALTER TABLE ORDERS_PRODUCT
    ADD CONSTRAINT PK_ORDERS_PRODUCT PRIMARY KEY (ORDERS_ID, PRODUCT_ID, OPTIONS_NAME_NO);

-- MEMBERS
ALTER TABLE "MEMBERS" 
    ADD CONSTRAINT "PK_MEMBERS" PRIMARY KEY (MEMBERS_NO)
    ADD CONSTRAINT "UQ_MEM_ID" UNIQUE (MEMBERS_ID)
    ADD CONSTRAINT "UQ_MEM_EMAIL" UNIQUE (MEMBERS_EMAIL)
    ADD CONSTRAINT "UQ_MEM_PHONE" UNIQUE (MEMBERS_PHONE)
    ADD CONSTRAINT "CK_MEM_TYPE" CHECK (MEMBERS_TYPE IN (1, 2))
    ADD CONSTRAINT "CK_MEM_STATUS" CHECK (MEMBERS_STATUS IN ('Y', 'N'));

-- PRODUCT_CART
ALTER TABLE "PRODUCT_CART" ADD CONSTRAINT "PK_PRODUCT_CART" PRIMARY KEY ("PRODUCT_ID", "MEMBERS_NO");

-- QNA
ALTER TABLE "QNA"
    ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("QNA_ID")
    ADD CONSTRAINT CK_QNA_TYPE CHECK (QNA_TYPE IN ('Q', 'A'))
    ADD CONSTRAINT CK_QNA_CONFIDENTIAL CHECK (QNA_CONFIDENTIAL IN ('N', 'Y'))
    ADD CONSTRAINT CK_QNA_STATUS CHECK (QNA_STATUS IN ('Y', 'N'));


-- MEDIA
ALTER TABLE "MEDIA"
    ADD CONSTRAINT "PK_MEDIA" PRIMARY KEY ("MEDIA_ID")
    ADD CONSTRAINT CK_MED_TYPE CHECK (MEDIA_TYPE IN (1, 2))
    ADD CONSTRAINT CK_MED_STATUS CHECK (MEDIA_STATUS IN('Y', 'N'));

-- REPLY
ALTER TABLE "REPLY"
    ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_ID")
    ADD CONSTRAINT CK_REP_STATUS CHECK (REPLY_STATUS IN ('Y', 'N'));

    
-- REVIEW
ALTER TABLE "REVIEW"
    ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_ID")
    ADD CONSTRAINT CK_REV_RATING CHECK (RATING IN (1, 2, 3, 4, 5))
    ADD CONSTRAINT CK_REV_STATUS CHECK (REVIEW_STATUS IN ('Y', 'N'));


-- TAG
ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY ("MEDIA_ID","PRODUCT_ID");

-- SCRAP
ALTER TABLE "SCRAP"
    ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY ("SCRAP_ID")
    ADD CONSTRAINT CK_SCR_STATUS CHECK (SCRAP_STATUS IN ('Y', 'N'));

----------------------------------- 외래키
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBERS_TO_BOARD" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE PRODUCT ADD CONSTRAINT "FK_MEMBERS_TO_PRODUCT" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "PRODUCT_OPTIONS" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_OPTIONS" FOREIGN KEY ("PDOPT_PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE OPTIONS_CATEGORY ADD CONSTRAINT "FK_PDOPT_TO_OPTCG" FOREIGN KEY ("OPTIONS_PDOPT_ID") REFERENCES "PRODUCT_OPTIONS";

ALTER TABLE OPTIONS_NAME ADD CONSTRAINT "FK_OPTCG_TO_OPTNAME" FOREIGN KEY ("OPTIONS_NAME_OPT_NO") REFERENCES "OPTIONS_CATEGORY";

ALTER TABLE "ORDERS" 
    ADD CONSTRAINT "FK_MEMBERS_TO_ORDERS" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE ORDERS_PRODUCT
    ADD CONSTRAINT FK_ORDERS_TO_ORDPD FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS
    ADD CONSTRAINT FK_PRODUCT_TO_ORDPD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT
    ADD CONSTRAINT FK_OPTNAME_TO_ORDPD FOREIGN KEY (OPTIONS_NAME_NO) REFERENCES OPTIONS_NAME;

ALTER TABLE "PRODUCT_CART" 
    ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_CART" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_PRODUCT_CART" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "QNA" 
    ADD CONSTRAINT "FK_PRODUCT_TO_QNA" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_QNA" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "MEDIA" 
    ADD CONSTRAINT "FK_BOARD_TO_MEDIA" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD"
    ADD CONSTRAINT "FK_MEMBERS_TO_MEDIA" FOREIGN KEY (MEMBERS_NO) REFERENCES MEMBERS
    ADD CONSTRAINT "FK_PRODUCT_TO_MEDIA" FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT;

ALTER TABLE "REPLY" 
    ADD CONSTRAINT "FK_BOARD_TO_REPLY" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_REPLY" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "REVIEW" 
    ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_REVIEW" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "TAG" 
    ADD CONSTRAINT "FK_MEDIA_TO_TAG" FOREIGN KEY ("MEDIA_ID") REFERENCES "MEDIA" ("MEDIA_ID")
    ADD CONSTRAINT "FK_PRODUCT_TO_TAG" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_MEMBERS_TO_SCRAP" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_BOARD_TO_SCRAP" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_MEDIA_TO_SCRAP" FOREIGN KEY ("MEDIA_ID") REFERENCES "MEDIA" ("MEDIA_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_PRODUCT_TO_SCRAP" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");
-- =====================================  시퀀스 ===============================================================================
-- BOARD
CREATE SEQUENCE SEQ_BODID NOCACHE;
-- BOARD-MEDIA
CREATE SEQUENCE SEQ_MEDID NOCACHE;
-- MEMBERS
CREATE SEQUENCE SEQ_MEMID NOCACHE;
-- ORDERS
CREATE SEQUENCE SEQ_ORDID NOCACHE;
-- PRODUCT
CREATE SEQUENCE SEQ_PDID NOCACHE;
-- PRODUCT_OPTIONS
CREATE SEQUENCE SEQ_PDOPTID NOCACHE;
-- OPTIONS_CATEGORY
CREATE SEQUENCE SEQ_OPTCG NOCACHE;
-- OPTIONS_NAME
CREATE SEQUENCE SEQ_OPTNAME NOCACHE;
-- QNA
CREATE SEQUENCE SEQ_QNAID NOCACHE;
-- REPLY
CREATE SEQUENCE SEQ_REPID NOCACHE;
-- REVIEW
CREATE SEQUENCE SEQ_REVID NOCACHE;
-- SCRAP
CREATE SEQUENCE SEQ_SCRID NOCACHE;
-- TAG
CREATE SEQUENCE SEQ_TAGID NOCACHE;
-- ===================================== 트리거 ====================================================================================
-- 주문 시 PRODUCT.STOCK(재고량) := PRODUCT.STOCK - ORDERS.ORDERS_AMOUNT값
CREATE OR REPLACE TRIGGER TRG_PRODUCT_STOCK_MINUS
AFTER INSERT ON ORDERS_PRODUCT
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET STOCK = STOCK - :NEW.AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/
-- 주문 시 PRODUCT.PRODUCT_SALES(누적 판매량) := PRODUCT.PRODUCT_SALES + ORDERS.ORDERS_AMOUNT
CREATE OR REPLACE TRIGGER TRG_PRODUCT_SALES
AFTER INSERT ON ORDERS_PRODUCT
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET PRODUCT_SALES = PRODUCT_SALES + :NEW.AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/
-- 상품 옵션명 등록 시 PRODUCT.STOCK := PRODUCT.STOCK + OPTIONS_NAME.OPTIONS_STOCK
CREATE OR REPLACE TRIGGER TRG_UPDATE_STOCK
AFTER INSERT ON OPTIONS_NAME
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET STOCK = STOCK + :NEW.OPTIONS_STOCK
    WHERE PRODUCT_ID IN (
        SELECT PDOPT_PRODUCT_ID 
        FROM PRODUCT_OPTIONS 
        WHERE PRODUCT_OPTIONS_ID = :NEW.OPTIONS_NAME_OPT_NO
    );
END;
/


-- ================================ 더미데이터 =============================================
----------------------------------------- MEMBERS ------------------------------------------
INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, MEMBERS_NAME, MEMBERS_BIRTH, MEMBERS_PHONE, MEMBERS_EMAIL, GENDER, MEMBERS_TYPE, COMPANY_NAME, REPRESENTATATIVE, COMPANY_PLACE, COMPANY_PHONE, COMPANY_EMAIL, REG_NUM, MEMBERS_STATUS)
VALUES (SEQ_MEMID.NEXTVAL, 'admin', '1234', '관리자', '1990-01-01', '010-1111-2222', 'admin@admin.com', 'M', 1, 'admin', '관리자', '서울시 강남구 역삼동', '02-111-1111', 'admin@kh.com', '111-11-11111', 'Y');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, MEMBERS_NAME, MEMBERS_BIRTH, MEMBERS_PHONE, MEMBERS_EMAIL, GENDER, MEMBERS_TYPE, COMPANY_NAME, REPRESENTATATIVE, COMPANY_PLACE, COMPANY_PHONE, COMPANY_EMAIL, REG_NUM, MEMBERS_STATUS)
VALUES (SEQ_MEMID.NEXTVAL, 'hyoyoungjjang', '1234', '김효영', '2001-01-01', '010-1234-1111', 'hyoyoungjjang@naver.com', 'M', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Y');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, MEMBERS_NAME, MEMBERS_BIRTH, MEMBERS_PHONE, MEMBERS_EMAIL, GENDER, MEMBERS_TYPE, COMPANY_NAME, REPRESENTATATIVE, COMPANY_PLACE, COMPANY_PHONE, COMPANY_EMAIL, REG_NUM, MEMBERS_STATUS)
VALUES (SEQ_MEMID.NEXTVAL, 'king', '1234', '주재완', '1999-01-01', '010-2222-3333', 'king@naver.com', 'M', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Y');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '먼데이하우스', '1234', '먼데이하우스');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '오가든', '1234', '오가든');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '큐브', '1234', '큐브');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '삼성전자', '1234', '삼성전자');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '크리넥스', '1234', '크리넥스');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '오트밀하우스', '1234', '오트밀하우스');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '립톤', '1234', '립톤');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '시디즈', '1234', '시디즈');

INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, COMPANY_NAME)
VALUES (SEQ_MEMID.NEXTVAL, '쿠첸', '1234', '쿠첸');

----------------------------------------- BOARD ------------------------------------------
INSERT INTO BOARD (BOARD_ID, BOARD_TITLE, BOARD_VIEWS, BOARD_CREATE_TIME, BOARD_INTRODUCTION ,BOARD_DESCRIPTION, FILTER_TYPE, FILTER_AREA,FILTER_FAMILY, FILTER_FIELD, FILTER_WORKER, MEMBERS_NO)
VALUES (SEQ_BODID.NEXTVAL, '오늘의집 클론 코딩', 100, SYSDATE, '우리집을 소개합니다', '블라블라', '아파트', 30, '싱글라이프', '리모델링' , '전문가', 2);

INSERT INTO BOARD (BOARD_ID, BOARD_TITLE, BOARD_VIEWS, BOARD_CREATE_TIME, BOARD_INTRODUCTION ,BOARD_DESCRIPTION, FILTER_TYPE, FILTER_AREA,FILTER_FAMILY, FILTER_FIELD, FILTER_WORKER, MEMBERS_NO)
VALUES (SEQ_BODID.NEXTVAL, '할 수 있다', 200, SYSDATE, '우당탕탕 프로젝트', '블라블라', '원룸', 7, '싱글라이프', '홈스타일링', '셀프/DIY', 1);

INSERT INTO BOARD (BOARD_ID, BOARD_TITLE, BOARD_VIEWS, BOARD_INTRODUCTION, BOARD_DESCRIPTION, FILTER_TYPE, FILTER_AREA, FILTER_FAMILY, FILTER_FIELD,  FILTER_WORKER, MEMBERS_NO)
VALUES (SEQ_BODID.NEXTVAL, '깔끔한 집의 비결은? 짱짱한 수납과 팬트리에서!', 3102, 
'안녕하세요. 초등학교 4학년 남자아이, 24개월 여자 아이와 "산솔집(@sanif_home)"에 살고 있는 맞벌이 부부입니다. 
저희 집은 산솔집이라 불리고 있습니다. 물, 식물, 곤충, 동물 등 세상 모든 것들의 시작이고 동식물 모두를 포용하는 산의 모습을 닮길 바라며 첫째 이름을 산이라고 지었어요. 둘째는 항상 푸르고 밝게 자라길 바라는 마음으로 솔이라고 지었고요. 그래서 두 아이의 이름을 따 산솔집이라 이름 지었습니다.',
'산솔집은 20년이 훌쩍 넘은 구축 아파트를 리모델링 했습니다. 구축으로 이사 올 때 주위에 많은 분들이 반대를 했지만 저희는 맞벌이 부부이기에 아이의 등하교와 학원 등 인프라가 잘 갖춰진 곳 위주로 찾아보았고, 최종적으로 중, 고등학교 시절 제가 살던 아파트로 결정을 하였습니다.
이 집으로 결정을 하게 된 가장 큰 이유는 집에서 학교까지 걸어서 1분! 뛰어가면 30초! 라는 엄청난 메리트가 있으며, 아파트 단지 내에 학교 입구가 있어서 차도를 건너지 않아도 된다는 점, 아파트 앞에는 상가가 밀집되어 있고 그 상가들에는 초 · 중 · 고 학원들이 즐비하여 아이를 키우기에 최고의 입지 환경이라는 결론을 지었습니다.
인터넷에 있는 도면 상태인데 가벽과 일부 확장을 진행하여 현재와는 조금 다른 모습입니다. ',
'아파트', 48, '취학 자녀와 함께', '리모델링' , '전문가', 1);

INSERT INTO BOARD (BOARD_ID, MEMBERS_NO,  BOARD_TITLE, BOARD_VIEWS, FILTER_TYPE, FILTER_AREA, FILTER_FIELD, FILTER_FAMILY,  FILTER_WORKER, FILTER_LOCAL, FILTER_PERIOD, FILTER_PERIOD_TYPE, FILTER_CONSTRUCTION_PRICE,  BOARD_INTRODUCTION, BOARD_DESCRIPTION)
VALUES(
SEQ_BODID.NEXTVAL, 1, '히든도어, 고민하지 마세요! 깔끔한 33평 화이트&우드', 3159, '아파트', 33, '리모델링', '싱글라이프', '전문가', '경기도 수원시' , 5, '주', 6500,
'안녕하세요, 오뉴디자인입니다. 오늘 소개해 드릴 현장은 수원시 권선구 금곡동 호반베르디움더센트럴 33평 A타입이에요.',
'기존 구조를 살펴보면 ㄷ자 형태의 주방의 좌우로 팬트리가 있는 평범한 레이아웃이었답니다. 고객님께선 화이트 톤에 우드를 포인트로 넣기를 바라셨고 11자 형태 대면형 주방에 대한 니즈가 있었어요. 전반적으로 정돈되고 깔끔한 공간을 원했습니다. 이러한 니즈를 충족시켜 드리고자 주방에는 MDF와 필름, 깔끔한 히든도어를 활용하여 11자 형태의 대면형 주방으로 레이아웃을 짜드렸어요. 여러 디테일이 숨겨진 따뜻한 공간 지금부터 함께 구경해 보실까요? 집의 테마인 화이트 & 우드와 맞게 전체적으로 밝은 톤으로 꾸며준 현관이에요. 문 앞에 걸려있는 감각적인 그림 덕분에 클라이언트의 취향이 현관에서부터 느껴집니다. '
);

INSERT INTO BOARD (BOARD_ID, MEMBERS_NO,  BOARD_TITLE, BOARD_VIEWS, FILTER_TYPE, FILTER_AREA, FILTER_FIELD, FILTER_FAMILY,  FILTER_WORKER, FILTER_LOCAL, BOARD_INTRODUCTION, BOARD_DESCRIPTION)
VALUES(
SEQ_BODID.NEXTVAL, 1, '장시간 지내는 거실 홈오피스, 싱그러움 한 방울 더했어요!', 4959, '아파트', 22, '홈스타일링', '신혼부부', '셀프/DIY', '서울특별시',
'안녕하세요?! 오늘의집 집들이에 두 번째 인사를 드리는 룰루랄라홈입니다.
처음 집들이는 갓 이사 왔을 때 장신 없이 올린지라 지금 보면 너무 어설프고 정신도 없고 했던 거 같아요. 처음 집들이 소개 후 5년이라는 시간이 흘렀는데요. 그 사이 이사를 가고 싶었지만 현실은 아직 같은 공간입니다.
하지만 5년 전과는 모든 물건이 하나 같은 게 없어요. 집 뼈대는 그대로인데 집안의 모든 물건이 바뀌었다고 해도 과언이 아닌 거 같습니다.
처음 인스타를 시작했을 땐 셀프 인테리어에 목적을 두었는데요. 하지만 셀프 인테리어의 한계를 느끼면 점점 셀프가 줄어들고 있어요. 하지만 작년에 작은 변화를 준 주방은 아직도 셀프 인테리어의 취지가 살아 있습니다. 자 그럼 룰루랄라홈이 처음과 어떻게 바뀌었는지 살펴 보실까요?',
'작은 거실이지만 큰 테이블과 함께 포기하지 못한 소파입니다. 거실 구조를 고려해서 모듈형의 소파를 구입했습니다. 그리고 소파 옆엔 작은 티 테이블을 두었습니다.'
);

INSERT INTO BOARD (BOARD_ID, MEMBERS_NO,  BOARD_TITLE, BOARD_VIEWS, FILTER_TYPE, FILTER_AREA, FILTER_FIELD, FILTER_FAMILY,  FILTER_WORKER, FILTER_LOCAL, FILTER_PERIOD, FILTER_PERIOD_TYPE, BOARD_INTRODUCTION, BOARD_DESCRIPTION)
VALUES(
SEQ_BODID.NEXTVAL, 1, '집에 원형 기둥이? 독특한 유럽식 구조로 깊이감이 있는 집', 4707, '아파트', 54, '리모델링', '아기가 있는 집', '반셀프', '경기도 용인시', 3, '주',
'안녕하세요, 저는 장난꾸러기 두 아들의 엄마이고 영상 만드는 일을 하고 있는 @hejhey_home입니다. 
처음 보는 독특한 구조에 반해 이사 온 지 3개월 정도 되었어요. 유행을 따르기보다 저희의 취향대로 따뜻하고 아늑한 분위기의 집을 만들고자 했습니다. 3번째임에도 가장 힘든 반셀프 인테리어였어요.
큰 작업들이 끝나고 잠시 쉬고 싶은 마음에 아직 미완성인 부분이 많지만, 완성은 살면서 천천히 하도록 하고 온라인 집들이부터 시작해 보겠습니다 :)',

'거실 쪽에서 바라본 현관 중문 모습입니다. 현관 중문은 유리가 없는 디자인으로 제작했습니다. 유리가 있었다면 집이 더 확장돼 보였겠지만, 집 안에서 현관문과 신발이 보이는 게 싫어 막았습니다.
이 집 구조의 이름이 ''유럽형''이라 거기에 맞춘다고 프렌치 도어를 제작했는데 저희 집의 간결한 가구들과 인테리어 컨셉에 비해 다소 화려한 느낌이 들긴 합니다. 
그래도 새로 유행하는 디자인보다는 오래도록 쓰인 디자인을 좋아하는지라 만족하고 있어요. 손잡이도 제가 직접 구매한 건데 나중에 심플한 걸로 교체할까 싶어요.'
);

INSERT INTO BOARD (BOARD_ID, MEMBERS_NO,  BOARD_TITLE, BOARD_VIEWS, FILTER_TYPE, FILTER_AREA, FILTER_FIELD, FILTER_FAMILY,  FILTER_WORKER, FILTER_LOCAL, BOARD_INTRODUCTION, BOARD_DESCRIPTION)
VALUES(
SEQ_BODID.NEXTVAL, 1, '무채색과 우드, 쇠테리어 포인트가 매력적인 3평 공간!', 2859, '기타', 3, '홈스타일링', '부모님과 함께 사는 집', '셀프/DIY', '경상남도 양산시',
'안녕하세요! 자전거 라이딩과 인테리어, 그리고 음악을 좋아하는 조경학과 대학생입니다. 이전에 <무채색 배경에 취향으로 색칠한 나의 작은 3평 방>이라는 온라인 집들이로 찾아뵌 적이 있는데요. 
이후에 또 바뀌었던 방 분위기를 소개해드리려고 이렇게 다시 집들이로 찾아뵙게 되었습니다.
계속 많이 업로드했던 방 사진이지만, 이렇게 한번에 모아서 정리해보고자 했어요. 그러면 지금부터 저의 집들이 시작하도록 하겠습니다~!',

'이전의 인테리어와는 조금 더 달라진 제 방이에요. 전체적으로 무채색에 식물과 우드로 포인트를 주려고 했습니다.
미니멀리즘으로 꾸미고 싶은데, 항상 욕심이 많다 보니 점점 갈수록 오브제나 물건들이 많아지는 느낌입니다..!'
);
----------------------------------------- PRODUCT ------------------------------------------
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, 'LG 냉장고', 3000000, 100, 500, 3, 5, 'LG전자에서 만든 냉장고입니다', SYSDATE, 1, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '동원 참치', 10000, 1000, 500, 3, 15, '맛있는 동원 참치', SYSDATE, 1, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '송월타올', 20000, 300, 500, 3, 8, '호텔 수건급 월드클래스 타올', SYSDATE, 1, 2);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '옷걸이', 8000, 250, 500, 3, '옷걸이가 8천원!', SYSDATE, 1, 3);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, 'CLOUD 아쿠아텍스 패브릭 호텔식 침대프레임 SS/Q/K/LK/CK',199000, 100, 100, 1, 66, '튼튼한 프레임 짱' , SYSDATE, 4, 1);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '방울토마토 오늘의가든 사은품용 비매품',100000, 200, 200, 1, 0, '맛있는 도마도 짱맛있다' , SYSDATE, 5, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '계절꽃 오늘의가든 사은품용 비매품',100000, 200, 200, 1, 0, '계절꽃 예쁘다' , SYSDATE, 5, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '[단독] NEW컬러 맞춤제작 블라인드 시스템 드레스룸',8100, 560, 100, 1, 41, '커다란 드레스룸' , SYSDATE, 6, 1);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '혜택가 189만원대 BESPOKE 무풍에어컨 AF17B7538GZRS 멀티형',2179000, 300, 100, 1, 26, '곧 여름이 옵니다' , SYSDATE, 7, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '3겹 순수소프트 롤화장지 메가롤 (37Mx24롤)x2팩',47300, 560, 100, 1, 22, '산뜻한 휴지' , SYSDATE, 8, 3);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '혜택가 174만 인증점 삼성 Q9000 멀티형 에어컨 AF17B6474TZRS 기본설치포함',1829000, 82, 100, 1, 25, '가전은 삼성' , SYSDATE, 7, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '[무료배송] (국내생산) 데이지 LED조명 3단 벙커 수납 서랍 침대 SS/Q',239000, 200, 100, 1, 40, '서랍이 있어야 수납이 잘된다' , SYSDATE, 9, 1);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '비스포크 키친핏 냉장고 RF60C9012AP 615리터 에센셜 4도어 색상선택 공식인증점',2354000, 87, 100, 1, 27, '비스포크 삼성 가전 최고' , SYSDATE, 7, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '아이스티 믹스 복숭아 1.5kg  8개',102000, 560, 100, 1, 32, '립톤 아이스티에 에스프레소 샷 추가하면 MZ' , SYSDATE, 10, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, 'T50 컴퓨터 책상 의자 화이트 (HLDA)',349000, 120, 100, 1, 5, '서울대 의자로 공부하면 알죠?' , SYSDATE, 11, 1);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '쿠폰가26.8만! 121+ 6인용 올스텐 IH전기압력밥솥 화이트 CRT-RPS0691W',289000, 210, 100, 1, 38, '밥솥은 쿠쿠아니고 쿠첸' , SYSDATE, 12, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '24년 신제품 세탁 건조가 하나로,비스포크 AI콤보 WD25DB8995BZ 25+15kg',3999000, 18, 100, 1, 0, '세탁기와 건조기의 혼연일체' , SYSDATE, 7, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '[맞춤]브라우니 린넨 암막커튼 핀형/아일렛형/형상기억 33색상',19800, 240, 100, 1, 39, '태양을 피하고 싶었어요' , SYSDATE, 9, 2);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '클레어 LED 2단 수납침대+매트선택 (SS/Q) 4colors',219000, 120, 100, 1, 30, '수납 공간을 효율적으로 사용하고 싶은 분을 위한 침대' , SYSDATE, 9, 1);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, SALE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '[주말특가] 삼성 81cm M5 S32CM501 삼탠바이미 패키지 OTT',439000, 120, 100, 1, 20, '세탁기와 건조기의 혼연일체' , SYSDATE, 7, 4);



----------------------------------------- PRODUCT_OPTIONS ------------------------------------------
INSERT INTO PRODUCT_OPTIONS (PRODUCT_OPTIONS_ID, PDOPT_PRODUCT_ID)
VALUES (SEQ_PDOPTID.NEXTVAL, 5);
INSERT INTO OPTIONS_CATEGORY (OPTIONS_NO, OPTIONS_PDOPT_ID, OPTIONS_CATEGORY)
VALUES (SEQ_OPTCG.NEXTVAL, 1, '사이즈');
INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
VALUES (SEQ_OPTNAME.NEXTVAL, 1, '슈퍼 싱글', 0, 100);
INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
VALUES (SEQ_OPTNAME.NEXTVAL, 1, '퀸/킹 공용', 100000, 100);
INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
VALUES (SEQ_OPTNAME.NEXTVAL, 1, 'LK/CK 공용', 150000, 100);

INSERT INTO PRODUCT_OPTIONS (PRODUCT_OPTIONS_ID, PDOPT_PRODUCT_ID)
VALUES (SEQ_PDOPTID.NEXTVAL, 6);
    INSERT INTO OPTIONS_CATEGORY (OPTIONS_NO, OPTIONS_PDOPT_ID, OPTIONS_CATEGORY)
    VALUES (SEQ_OPTCG.NEXTVAL, 2, '종류');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 2, '스테비아 방울 토마토 500g', 0, 50);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 2, '스테비아 방울 토마토 500g + 500g', 21000, 50);

INSERT INTO PRODUCT_OPTIONS (PRODUCT_OPTIONS_ID, PDOPT_PRODUCT_ID)
VALUES (SEQ_PDOPTID.NEXTVAL, 7);
    INSERT INTO OPTIONS_CATEGORY (OPTIONS_NO, OPTIONS_PDOPT_ID, OPTIONS_CATEGORY)
    VALUES (SEQ_OPTCG.NEXTVAL, 3, '꽃 사이즈 선택');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 3, '계절꽃믹스-소', 0, 50);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 3, '계절꽃믹스-중', 11000, 50);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_PRICE, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 3, '계절꽃믹스-대', 10000, 50);

INSERT INTO PRODUCT_OPTIONS (PRODUCT_OPTIONS_ID, PDOPT_PRODUCT_ID)
VALUES (SEQ_PDOPTID.NEXTVAL, 8);
    INSERT INTO OPTIONS_CATEGORY (OPTIONS_NO, OPTIONS_PDOPT_ID, OPTIONS_CATEGORY)
    VALUES (SEQ_OPTCG.NEXTVAL, 4, '프레임 색상');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME)
        VALUES (SEQ_OPTNAME.NEXTVAL, 4, '화이트');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME)
        VALUES (SEQ_OPTNAME.NEXTVAL, 4, '실버');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME)
        VALUES (SEQ_OPTNAME.NEXTVAL, 4, '블랙');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME)
        VALUES (SEQ_OPTNAME.NEXTVAL, 4, '골드');
    INSERT INTO OPTIONS_CATEGORY (OPTIONS_NO, OPTIONS_PDOPT_ID, OPTIONS_CATEGORY)
    VALUES (SEQ_OPTCG.NEXTVAL, 4, '선반 색상');
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 5, '화이트', 20);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 5, '내추럴', 20);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 5, '월넛', 20);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 5, '핑크', 20);
        INSERT INTO OPTIONS_NAME (OPTIONS_NAME_NO, OPTIONS_NAME_OPT_NO, OPTIONS_NAME, OPTIONS_STOCK)
        VALUES (SEQ_OPTNAME.NEXTVAL, 5, '민트', 20);

-- ORDERS 테이블에 더미 데이터 삽입
--INSERT INTO ORDERS (ORDERS_ID, RECIPIENT_NAME, RECIPIENT_PHONE, RECIPIENT_EMAIL, RECIPIENT_ADDRESS, RECIPIENT_POSTCODE, ORDERS_DATE, ORDERS_AMOUNT, PAYMENT_AMOUNT, REQURIEDMENT, PRODUCT_ID, MEMBERS_NO, ORDERS_DELIVERY_STATUS)
--VALUES (SEQ_ORDID.NEXTVAL, '김효영', '010-1234-1111', 'hyoyoungjjang@naver.com', '서울시 동대문구 회기동', 12345, SYSDATE, 3, 30000, '배송시 벨 눌려주세요', 3, 2, '배송준비중');

INSERT INTO ORDERS
(ORDERS_ID, MEMBERS_NO, RECIPIENT_NAME, RECIPIENT_PHONE, RECIPIENT_EMAIL, RECIPIENT_ADDRESS, RECIPIENT_POSTCODE, ORDERS_DATE, TOTAL_PRICE, ARRIVAL_DATE, REQURIEDMENT, ORDERS_DELIVERY_STATUS)
VALUES
(SEQ_ORDID.NEXTVAL, 2, '김효영', '010-1234-1111', 'hyoyoungjjang@naver.com', '서울시 동대문구 회기동', 12345, SYSDATE, 200000, '2024-04-26' ,'배송시 벨 눌려주세요', '배송준비중');

INSERT INTO ORDERS_PRODUCT
(ORDERS_ID, PRODUCT_ID, OPTIONS_NAME_NO, AMOUNT)
VALUES
(1, 6, 4, 2);

--SELECT RECIPIENT_NAME, RECIPIENT_PHONE, RECIPIENT_EMAIL, RECIPIENT_ADDRESS, RECIPIENT_POSTCODE,
--ORDERS_DATE, TOTAL_PRICE, ARRIVAL_DATE, REQURIEDMENT, ORDERS_DELIVERY_STATUS, ORDERS_STATUS, PRODUCT_NAME, OPTIONS_CATEGORY , OPTIONS_NAME, ( PRODUCT_PRICE + OPTIONS_PRICE ) * AMOUNT AS "PRICE"
--FROM ORDERS
--JOIN ORDERS_PRODUCT USING(ORDERS_ID)
--JOIN PRODUCT USING (PRODUCT_ID)
--JOIN OPTIONS_NAME USING (OPTIONS_NAME_NO)
--JOIN OPTIONS_CATEGORY ON (OPTIONS_NAME_OPT_NO = OPTIONS_NO);

----------------------------------------- PRODUCT_CART ------------------------------------------
INSERT INTO PRODUCT_CART (PRODUCT_ID, MEMBERS_NO, CART_AMOUNT)
VALUES (1, 1, 1);
INSERT INTO PRODUCT_CART (PRODUCT_ID, MEMBERS_NO, CART_AMOUNT)
VALUES (2, 1, 10);
INSERT INTO PRODUCT_CART (PRODUCT_ID, MEMBERS_NO, CART_AMOUNT)
VALUES (3, 1, 10);
INSERT INTO PRODUCT_CART (PRODUCT_ID, MEMBERS_NO, CART_AMOUNT)
VALUES (4, 1, 5);
----------------------------------------- QNA ------------------------------------------
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '냉장고가 잘 작동하나요?', 'N', 1, 2);
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '네 잘 작동합니다', 'A', 'N', 1, 1);
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '냉냉', 'Q', 'N', 1, 2);
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '장장', 'A', 'N', 1, 1);
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '동', 'Q', 'N', 2, 2);
INSERT INTO QNA (QNA_ID, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, '원', 'A', 'N', 2, 1);
----------------------------------------- MEDIA ------------------------------------------
--------------------- 집들이
-- 썸네일
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 1, 1, 'thumbnail-main-01.png', 'thumbnail-main-01.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 2, 1, 'thumbnail-main-02.png', 'thumbnail-main-02.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 3, 1, 'thumbnail-main-03.png', 'thumbnail-main-03.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 4, 1, 'thumbnail-main-04.png', 'thumbnail-main-04.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 5, 1, 'thumbnail-main-05.png', 'thumbnail-main-05.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 6, 1, 'thumbnail-main-06.png', 'thumbnail-main-06.png', 'resources/img/community/communityMain/', 1);
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 7, 1, 'thumbnail-main-07.png', 'thumbnail-main-07.png', 'resources/img/community/communityMain/', 1);

-- 게시글 사진
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 3, 1, 'boardContent03.png', 'boardContent03.png', 'resources/img/community/communityPage/', 2);

INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 4, 1, 'boardContent04.png', 'boardContent04.png', 'resources/img/community/communityPage/', 2);

INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 5, 1, 'boardContent05.png', 'boardContent05.png', 'resources/img/community/communityPage/', 2);

INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 6, 1, 'boardContent06.png', 'boardContent06.png', 'resources/img/community/communityPage/', 2);

INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 7, 1, 'boardContent07-1.png', 'boardContent07-1.png', 'resources/img/community/communityPage/', 2);

INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 7, 1, 'boardContent07-2.png', 'boardContent07-2.png', 'resources/img/community/communityPage/', 2);


-- 상품 썸네일
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 1, 1, 'productMain01.png', 'productMain01.png', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 2, 1, 'productMain02.png', 'productMain02.png', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 3, 1, 'productMain03.png', 'productMain03.png', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 4, 1, 'productMain04.png', 'productMain04.png', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 5, 1, 'productMain05.jpg', 'productMain05.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 6, 1, 'productMain06.jpg', 'productMain06.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 7, 1, 'productMain07.jpg', 'productMain07.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 8, 1, 'productMain08.jpg', 'productMain08.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 9, 1, 'productMain09.jpg', 'productMain09.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 10, 1, 'productMain10.jpg', 'productMain10.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 11, 1, 'productMain11.jpg', 'productMain11.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 12, 1, 'productMain12.jpg', 'productMain12.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 13, 1, 'productMain13.jpg', 'productMain13.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 14, 1, 'productMain14.jpg', 'productMain14.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 15, 1, 'productMain15.jpg', 'productMain15.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 16, 1, 'productMain16.jpg', 'productMain16.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 17, 1, 'productMain17.jpg', 'productMain17.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 18, 1, 'productMain18.jpg', 'productMain18.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 19, 1, 'productMain19.jpg', 'productMain19.jpg', 'resources/img/product/', 1);
INSERT INTO MEDIA (MEDIA_ID, PRODUCT_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 20, 1, 'productMain20.jpg', 'productMain20.jpg', 'resources/img/product/', 1);


-- 프로필 사진
INSERT INTO MEDIA (MEDIA_ID, MEMBERS_NO, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 1, 1, 'user.png', 'user.png', 'resources/img/common/', 3);
INSERT INTO MEDIA (MEDIA_ID, MEMBERS_NO, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 2, 1, 'user.png', 'user.png', 'resources/img/common/', 3);
INSERT INTO MEDIA (MEDIA_ID, MEMBERS_NO, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 3, 1, 'user.png', 'user.png', 'resources/img/common/', 3);

----------------------------------------- REPLY ------------------------------------------
INSERT INTO REPLY (REPLY_ID, REPLY_CONTENT, REPLY_CREATE_DATE, BOARD_ID, MEMBERS_NO) VALUES (SEQ_REPID.NEXTVAL, '퍼가요', SYSDATE, 1, 3);
INSERT INTO REPLY (REPLY_ID, REPLY_CONTENT, REPLY_CREATE_DATE, BOARD_ID, MEMBERS_NO) VALUES (SEQ_REPID.NEXTVAL, '잘보고갑니다', SYSDATE, 2, 3);

----------------------------------------- REVIEW ------------------------------------------
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_CONTENT, HELPFUL, REVIEW_CREATE_DATE, PRODUCT_ID, MEMBERS_NO)
    VALUES (SEQ_REVID.NEXTVAL, 5, '역시 가전은 LG!', '도움이 됨', SYSDATE, 1, 2);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_CONTENT, HELPFUL, REVIEW_CREATE_DATE, PRODUCT_ID, MEMBERS_NO)
    VALUES (SEQ_REVID.NEXTVAL, 4, '참치는 동원', '도움이 됨', SYSDATE, 2, 3);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_CONTENT, HELPFUL, REVIEW_CREATE_DATE, PRODUCT_ID, MEMBERS_NO)
    VALUES (SEQ_REVID.NEXTVAL, 4, '타월은 송월', '도움이 됨', SYSDATE, 3, 3);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_CONTENT, HELPFUL, REVIEW_CREATE_DATE, PRODUCT_ID, MEMBERS_NO)
    VALUES (SEQ_REVID.NEXTVAL, 3, '옷걸이가 맛있어요', '도움이 됨', SYSDATE, 4, 3);
----------------------------------------- TAG ------------------------------------------
INSERT INTO TAG (MEDIA_ID, PRODUCT_ID, TAG_X, TAG_Y)
VALUES (1, 1, 50, 50);

----------------------------------------- SCRAP ------------------------------------------
INSERT INTO SCRAP (SCRAP_ID, SCRAP_TYPE, MEMBERS_NO, PRODUCT_ID)
VALUES (SEQ_SCRID.NEXTVAL, 1, 1, 1);
INSERT INTO SCRAP (SCRAP_ID, SCRAP_TYPE, MEMBERS_NO, MEDIA_ID)
VALUES (SEQ_SCRID.NEXTVAL, 2, 2, 1);
INSERT INTO SCRAP (SCRAP_ID, SCRAP_TYPE, MEMBERS_NO, BOARD_ID)
VALUES (SEQ_SCRID.NEXTVAL, 3, 3, 1);

COMMIT;