 DROP TABLE BOARD CASCADE CONSTRAINT;

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER,
	"BOARD_TITLE"	VARCHAR2(255) CONSTRAINT NT_BOD_TITLE NOT NULL,
	"BOARD_VIEWS"	NUMBER	DEFAULT 0,
	"BOARD_CREATE_TIME"	DATE DEFAULT SYSDATE,
	"BOARD_MODIFY_TIME"	DATE NULL,
	"BOARD_COVER_SRC"	VARCHAR2(255) NULL,
	"BOARD_CONTENT"	VARCHAR2(4000) CONSTRAINT NT_BOD_CONTENT NOT NULL,
	"FILTER_TYPE"	VARCHAR2(20) CONSTRAINT NT_BOD_FI_TYPE NOT NULL,
	"FILTER_AREA"	NUMBER	CONSTRAINT NT_BOD_FI_AREA NOT NULL,
	"FILTER_NUM"	NUMBER	NULL,
	"FILTER_DIRECTION"	VARCHAR2(20) NULL,
	"FILTER_PAST"	VARCHAR2(20) NULL,
	"FILTER_LOCAL"	VARCHAR2(255) NULL,
	"FILTER_FAMILY"	VARCHAR2(255) CONSTRAINT NT_BOD_FI_FAM NOT NULL,
	"FILTER_PET"	VARCHAR2(20) NULL,
	"FILTER_FAMILY_MEM_CNT"	NUMBER	NULL,
	"FILTER_FIELD"	VARCHAR2(20) NULL,
	"FILTER_WORKER"	VARCHAR2(20) CONSTRAINT NT_BOD_FI_WORKER NOT NULL,
	"FILTER_RANGE"	VARCHAR2(20) NULL,
	"FILTER_PERIOD"	NUMBER NULL,
	"FILTER_PERIOD_TYPE" VARCHAR2(20) NULL,
	"FILTER_CONSTRUCTION_PRICE"	NUMBER NULL,
	"FILTER_STYLE_PRICE" NUMBER NULL,
	"FILTER_URL" VARCHAR2(255) NULL,
	"FILTER_COPYRIGHT"	VARCHAR2(20) NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT NT_BOD_MEMNO NOT NULL,
    BOARD_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_VIEWS" IS '조회수';
COMMENT ON COLUMN "BOARD"."BOARD_CREATE_TIME" IS '생성일';
COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_TIME" IS '수정일';
COMMENT ON COLUMN "BOARD"."BOARD_COVER_SRC" IS '커버 사진 주소';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';
COMMENT ON COLUMN "BOARD"."FILTER_TYPE" IS '주거형태';
COMMENT ON COLUMN "BOARD"."FILTER_AREA" IS '평수';
COMMENT ON COLUMN "BOARD"."FILTER_NUM" IS '방개수';
COMMENT ON COLUMN "BOARD"."FILTER_DIRECTION" IS '방향';
COMMENT ON COLUMN "BOARD"."FILTER_PAST" IS '준공연차';
COMMENT ON COLUMN "BOARD"."FILTER_LOCAL" IS '지역';
COMMENT ON COLUMN "BOARD"."FILTER_FAMILY" IS '가족형태';
COMMENT ON COLUMN "BOARD"."FILTER_PET" IS '반려동물';
COMMENT ON COLUMN "BOARD"."FILTER_FAMILY_MEM_CNT" IS '구성원수';
COMMENT ON COLUMN "BOARD"."FILTER_FIELD" IS '작업분야';
COMMENT ON COLUMN "BOARD"."FILTER_WORKER" IS '작업자';
COMMENT ON COLUMN "BOARD"."FILTER_RANGE" IS '시공범위';
COMMENT ON COLUMN "BOARD"."FILTER_PERIOD" IS '기간';
COMMENT ON COLUMN "BOARD"."FILTER_PERIOD_TYPE" IS '주 또는 개월';
COMMENT ON COLUMN "BOARD"."FILTER_CONSTRUCTION_PRICE" IS '공사 예산';
COMMENT ON COLUMN "BOARD"."FILTER_STYLE_PRICE" IS '스타일링예산';
COMMENT ON COLUMN "BOARD"."FILTER_URL" IS '링크';
COMMENT ON COLUMN "BOARD"."FILTER_COPYRIGHT" IS '저작권자';
COMMENT ON COLUMN "BOARD"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN BOARD.BOARD_STATUS IS '게시글 상태(현존 여부)';
-----------------------------------------------------------------
DROP TABLE "PRODUCT" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT" (
	"PRODUCT_ID" NUMBER,
	"PRODUCT_NAME"	VARCHAR2(100) CONSTRAINT NT_PD_NAME NOT NULL,
	"PRODUCT_PRICE"	NUMBER CONSTRAINT NT_PD_PRICE NOT NULL,
	"PRODUCT_SALES"	NUMBER DEFAULT 0,
	"STOCK"	NUMBER CONSTRAINT NT_PD_STOCK NOT NULL,
	"DELIVERY_DATE"	NUMBER DEFAULT 1,
	"SALE"	NUMBER DEFAULT 0,
	"PRODUCT_CONTENT"	VARCHAR2(4000) CONSTRAINT NT_PD_CONTENT NOT NULL,
	"PRODUCT_CREATE_TIME" DATE DEFAULT SYSDATE,
	"PRODUCT_MODIFY_TIME" DATE NULL,
	"MEMBERS_NO" NUMBER CONSTRAINT NT_PD_MEMNO NOT NULL,
	"PRODUCT_DELIVERY_PRICE" NUMBER	DEFAULT 0 NULL,
    "PRODUCT_CATEGORY" NUMBER CONSTRAINT NT_PD_CATEGORY NOT NULL,
    PRODUCT_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품명';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_PRICE" IS '가격';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_SALES" IS '누적판매량';
COMMENT ON COLUMN "PRODUCT"."STOCK" IS '재고수량';
COMMENT ON COLUMN "PRODUCT"."DELIVERY_DATE" IS '배송소요일';
COMMENT ON COLUMN "PRODUCT"."SALE" IS '할인율';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CREATE_TIME" IS '생성일';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_MODIFY_TIME" IS '수정일';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_CATEGORY" IS '카테고리';
COMMENT ON COLUMN "PRODUCT"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_DELIVERY_PRICE" IS '배송비';
--------------------------------------------------------------------
DROP TABLE "PRODUCT_OPTIONS" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT_OPTIONS" (
	"PRODUCT_OPTIONS_ID" NUMBER,
	"PRODUCT_OPTIONS_CONTENT" VARCHAR2(4000) CONSTRAINT NT_PDOPT_CONTENT NOT NULL,
	"PRODUCT_OPTIONS_PRICE"	NUMBER CONSTRAINT NT_PDOPT_PRICE NOT NULL,
	"PRODUCT_OPTIONS_STOCK"	NUMBER CONSTRAINT NT_PDOPT_STOCK NOT NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_PDOPT_PDIDNOT NULL,
    PRODUCT_OPTIONS_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_ID" IS '상품옵션ID';
COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_CONTENT" IS '옵션내용';
COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_PRICE" IS '옵션가격';
COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_OPTIONS_STOCK" IS '옵션재고';
COMMENT ON COLUMN "PRODUCT_OPTIONS"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN PRODUCT_OPTIONS.PRODUCT_OPTIONS_STATUS IS '옵션 유효 여부';
-------------------------------------------------------------------
DROP TABLE ORDERS CASCADE CONSTRAINT;

CREATE TABLE "ORDERS" (
	"ORDERS_ID"	NUMBER,
	"RECIPIENT_NAME"	VARCHAR2(20) CONSTRAINT NT_ORD_NAME NOT NULL,
	"RECIPIENT_PHONE"	VARCHAR2(50) CONSTRAINT NT_ORD_PHONE NOT NULL,
	"RECIPIENT_EMAIL"	VARCHAR2(255) NULL,
	"RECIPIENT_ADDRESS"	VARCHAR(255) CONSTRAINT NT_ORD_RE_ADDRESS NOT NULL,
	"RECIPIENT_POSTCODE" NUMBER CONSTRAINT NT_ORD_RE_POSTCODE NOT NULL,
	"ORDERS_DATE" DATE DEFAULT SYSDATE,
	"ORDERS_AMOUNT" NUMBER CONSTRAINT NT_ORD_AMOUNT NOT NULL,
	"PAYMENT_AMOUNT"	NUMBER CONSTRAINT NT_ORD_PAYMENT NOT NULL,
	"ARRIVAL_DATE" DATE DEFAULT SYSDATE,
	"REQURIEDMENT"	VARCHAR2(255) NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_ORD_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_ORD_MEMNO NOT NULL,
	"ORDERS_DELIVERY_STATUS"	VARCHAR2(20) CONSTRAINT NT_ORD_DELI_STATUS NOT NULL,
    ORDERS_STATUS CHAR(1) DEFAULT 'Y'
);
-- 주문 취소 ???? -> 트리거 걸려있기 때문에 까다로워짐

COMMENT ON COLUMN "ORDERS"."ORDERS_ID" IS '주문번호';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_NAME" IS '수령인';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_PHONE" IS '수령인전화번호';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_EMAIL" IS '수령인이메일';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_ADDRESS" IS '수령인주소';
COMMENT ON COLUMN "ORDERS"."RECIPIENT_POSTCODE" IS '수령인우편번호';
COMMENT ON COLUMN "ORDERS"."ORDERS_DATE" IS '주문일자';
COMMENT ON COLUMN "ORDERS"."ORDERS_AMOUNT" IS '주문수량';
COMMENT ON COLUMN "ORDERS"."PAYMENT_AMOUNT" IS '지불금액';
COMMENT ON COLUMN "ORDERS"."ARRIVAL_DATE" IS '배송완료일';
COMMENT ON COLUMN "ORDERS"."REQURIEDMENT" IS '요청사항';
COMMENT ON COLUMN "ORDERS"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "ORDERS"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "ORDERS"."ORDERS_DELIVERY_STATUS" IS '배송상태';
COMMENT ON COLUMN ORDERS.ORDERS_STATUS IS '주문 유효 여부';
-------------------------------------------------------------
DROP TABLE "MEMBERS" CASCADE CONSTRAINT;

CREATE TABLE "MEMBERS" (
	"MEMBERS_NO"	NUMBER,
	"MEMBERS_ID"	VARCHAR2(20) CONSTRAINT NT_MEM_ID NOT NULL,
	"MEMBERS_PWD"	VARCHAR2(20) CONSTRAINT NT_MEM_PWD NOT NULL,
	"MEMBERS_NAME"	VARCHAR2(20),
	"MEMBERS_BIRTH"	DATE NULL,
	"MEMBERS_PHONE"	VARCHAR2(20),
	"MEMBERS_EMAIL"	VARCHAR2(50),
	"GENDER" VARCHAR2(20) NULL,
	"MEMBERS_TYPE"	NUMBER DEFAULT 1,
	"COMPANY_NAME"	VARCHAR2(255) NULL,
	"REPRESENTATATIVE"	VARCHAR2(20) NULL,
	"COMPANY_PLACE"	VARCHAR2(255) NULL,
	"COMPANY_PHONE"	VARCHAR2(20) NULL,
	"COMPANY_EMAIL"	VARCHAR2(255) NULL,
	"REG_NUM"	VARCHAR2(20) NULL,
    MEMBERS_ENROLL_TIME DATE DEFAULT SYSDATE,
    MEMBERS_MODIFY_TIME DATE NULL,
    MEMBERS_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "MEMBERS"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_ID" IS '회원아이디';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_PWD" IS '회원비밀번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_NAME" IS '회원닉네임';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_BIRTH" IS '회원생년월일';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_PHONE" IS '회원전화번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_EMAIL" IS '회원이메일';
COMMENT ON COLUMN "MEMBERS"."GENDER" IS '회원성별';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_TYPE" IS '회원타입';
COMMENT ON COLUMN "MEMBERS"."COMPANY_NAME" IS '상호';
COMMENT ON COLUMN "MEMBERS"."REPRESENTATATIVE" IS '대표자';
COMMENT ON COLUMN "MEMBERS"."COMPANY_PLACE" IS '사업장소재지';
COMMENT ON COLUMN "MEMBERS"."COMPANY_PHONE" IS '회사전화번호';
COMMENT ON COLUMN "MEMBERS"."COMPANY_EMAIL" IS '회사이메일';
COMMENT ON COLUMN "MEMBERS"."REG_NUM" IS '사업자등록번호';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_ENROLL_TIME" IS '회원 가입 일시';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_MODIFY_TIME" IS '회원 정보 수정 일시';
COMMENT ON COLUMN "MEMBERS"."MEMBERS_STATUS" IS '회원 상태';
-----------------------------------------------------------
DROP TABLE "PRODUCT_CART" CASCADE CONSTRAINT;

CREATE TABLE "PRODUCT_CART" (
	"PRODUCT_ID" NUMBER CONSTRAINT NT_PDC_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_PDC_MEMNO NOT NULL,
	"QUANTITY"	NUMBER CONSTRAINT NT_PDC_QUAN NOT NULL
);
-- 삭제 시 DELETE
COMMENT ON COLUMN "PRODUCT_CART"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "PRODUCT_CART"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "PRODUCT_CART"."QUANTITY" IS '수량';
------------------------------------------------------------------
DROP TABLE "QNA";

CREATE TABLE "QNA" (
	"QNA_ID" NUMBER,
	"QNA_ISSUE_DATE" DATE DEFAULT SYSDATE,
	"QNA_CONTENT" VARCHAR2(4000) NULL,
	"QNA_TYPE"	CHAR(1)	DEFAULT 'Q',
	"QNA_CONFIDENTIAL"	CHAR(1)	DEFAULT 'N',
	"PRODUCT_ID" NUMBER CONSTRAINT NT_QNA_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_QNA_MEMNO NOT NULL,
    QNA_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "QNA"."QNA_ID" IS '질답ID';
COMMENT ON COLUMN "QNA"."QNA_ISSUE_DATE" IS '작성일';
COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '내용';
COMMENT ON COLUMN "QNA"."QNA_TYPE" IS '질답타입';
COMMENT ON COLUMN "QNA"."QNA_CONFIDENTIAL" IS '비밀글여부';
COMMENT ON COLUMN "QNA"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "QNA"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN QNA.QNA_STATUS IS '질답 상태';
---------------------------------------------------------------
DROP TABLE "MEDIA" CASCADE CONSTRAINT;

CREATE TABLE MEDIA (
	MEDIA_ID NUMBER,
    BOARD_ID NUMBER,
    MEMBERS_NO NUMBER,
    PRODUCT_ID NUMBER,
    MEDIA_TYPE NUMBER CONSTRAINT NT_MED_TYPE NOT NULL,
	ORIGIN_NAME VARCHAR2(255) CONSTRAINT NT_MED_ORIGIN NOT NULL,
    CHANGE_NAME VARCHAR2(255) CONSTRAINT NT_MED_CHANGE NOT NULL,
    FILE_PATH	VARCHAR2(1000) CONSTRAINT NT_MED_FILE_PATH NOT NULL,
    FILE_LEVEL NUMBER DEFAULT '2' CONSTRAINT NT_MED_LEVEL NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE,
    MEDIA_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "MEDIA"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "MEDIA"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "MEDIA".MEMBERS_NO IS '회원 번호';
COMMENT ON COLUMN "MEDIA".PRODUCT_ID IS '상품 번호';
COMMENT ON COLUMN "MEDIA"."MEDIA_TYPE" IS '사진(1) / 동영상(2)';
COMMENT ON COLUMN "MEDIA".ORIGIN_NAME IS '원본명';
COMMENT ON COLUMN "MEDIA".CHANGE_NAME IS '수정명';
COMMENT ON COLUMN "MEDIA".FILE_PATH IS '미디어 저장 경로';
COMMENT ON COLUMN "MEDIA".FILE_LEVEL IS '썸네일(1)/개별이미지(2)/프로필사진(3)';
COMMENT ON COLUMN MEDIA.MEDIA_STATUS IS '미디어 상태';
COMMENT ON COLUMN MEDIA.UPLOAD_DATE IS '미디어 게시일';
------------------------------------------------------------------
DROP TABLE "REPLY" CASCADE CONSTRAINT;

CREATE TABLE "REPLY" (
	"REPLY_ID"	NUMBER,
	"REPLY_TEXT" VARCHAR2(4000) CONSTRAINT NT_REP_TEXT NOT NULL,
	"REPLY_CREATE_DATE"	DATE DEFAULT SYSDATE,
	"REPLY_MODIFT_DATE"	DATE NULL,
	"BOARD_ID"	NUMBER CONSTRAINT NT_REP_BODID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_REP_MEMNO NOT NULL,
    REPLY_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "REPLY"."REPLY_ID" IS '댓글ID';
COMMENT ON COLUMN "REPLY"."REPLY_TEXT" IS '댓글 텍스트';
COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '생성일';
COMMENT ON COLUMN "REPLY"."REPLY_MODIFT_DATE" IS '수정일';
COMMENT ON COLUMN "REPLY"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "REPLY"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN REPLY.REPLY_STATUS IS '댓글 상태';
---------------------------------------------------------------
DROP TABLE "REVIEW" CASCADE CONSTRAINT;

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	NUMBER,
	"RATING"	NUMBER	CONSTRAINT NT_REV_RATING NOT NULL,
	"REVIEW_IMG"	VARCHAR2(255) CONSTRAINT NT_REV_IMG NOT NULL,
	"REVIEW_DETAIL"	VARCHAR2(4000) CONSTRAINT NT_REV_DETAIL NOT NULL,
	"HELPFUL"	VARCHAR(255) NULL,
	"REVIEW_CREATE_DAY"	DATE DEFAULT SYSDATE,
	"REVIEW_MODIFT_DAY"	DATE DEFAULT SYSDATE NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_REV_PDID NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT NT_REV_MEMNO NOT NULL,
    REVIEW_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰ID';
COMMENT ON COLUMN "REVIEW"."RATING" IS '별점';
COMMENT ON COLUMN "REVIEW"."REVIEW_IMG" IS '리뷰이미지';
COMMENT ON COLUMN "REVIEW"."REVIEW_DETAIL" IS '리뷰내용';
COMMENT ON COLUMN "REVIEW"."HELPFUL" IS '도움이돼요';
COMMENT ON COLUMN "REVIEW"."REVIEW_CREATE_DAY" IS '생성일';
COMMENT ON COLUMN "REVIEW"."REVIEW_MODIFT_DAY" IS '수정일';
COMMENT ON COLUMN "REVIEW"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "REVIEW"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN REVIEW.REVIEW_STATUS IS '리뷰 상태';
--------------------------------------------------------------------
DROP TABLE "TAG" CASCADE CONSTRAINT;

CREATE TABLE "TAG" (
	"MEDIA_ID"	NUMBER CONSTRAINT NT_TAG_MEDID NOT NULL,
	"PRODUCT_ID" NUMBER CONSTRAINT NT_TAG_PDOD  NOT NULL,
	"TAG_X"	NUMBER CONSTRAINT "NT_TAG_X" NOT NULL,
	"TAG_Y"	NUMBER CONSTRAINT "NT_TAG_Y" NOT NULL
);
-- 삭제 시 DELETE
COMMENT ON COLUMN "TAG"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "TAG"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "TAG"."TAG_X" IS '태그  X  좌표';
COMMENT ON COLUMN "TAG"."TAG_Y" IS '태그 Y 좌표';
------------------------------------------------------------
DROP TABLE "SCRAP" CASCADE CONSTRAINT ;

CREATE TABLE "SCRAP" (
	"SCRAP_ID"	NUMBER,
	"SCRAP_TYPE" NUMBER CONSTRAINT "NT_SCRAP_TYPE" NOT NULL,
	"MEMBERS_NO"	NUMBER CONSTRAINT "NT_SCRAP_MEMNO" NOT NULL,
	"BOARD_ID"	NUMBER,
	"MEDIA_ID"	NUMBER,
	"PRODUCT_ID" NUMBER,
	"SCRAP_CREATE_TIME"	DATE DEFAULT SYSDATE,
	"SCRAP_MODIFY_TIME"	DATE,
    SCRAP_STATUS CHAR(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "SCRAP"."SCRAP_ID" IS '스크랩ID';
COMMENT ON COLUMN "SCRAP"."SCRAP_TYPE" IS '스크랩타입';
COMMENT ON COLUMN "SCRAP"."MEMBERS_NO" IS '회원번호';
COMMENT ON COLUMN "SCRAP"."BOARD_ID" IS '게시글ID';
COMMENT ON COLUMN "SCRAP"."MEDIA_ID" IS '미디어ID';
COMMENT ON COLUMN "SCRAP"."PRODUCT_ID" IS '상품ID';
COMMENT ON COLUMN "SCRAP"."SCRAP_CREATE_TIME" IS '스크랩생성일';
COMMENT ON COLUMN "SCRAP"."SCRAP_MODIFY_TIME" IS '스크랩수정일';
COMMENT ON COLUMN SCRAP.SCRAP_STATUS IS '스크랩 유효 여부';
--==============================================================
-- 제약 조건 설정 부분(외래키 제외)
-- 게시글
ALTER TABLE "BOARD"
    ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (BOARD_ID)
    ADD CONSTRAINT CK_BOD_STATUS CHECK (BOARD_STATUS IN ('Y', 'N'));
    
-- 상품
ALTER TABLE "PRODUCT" 
    ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
    ADD CONSTRAINT UQ_PD_NAME UNIQUE (PRODUCT_NAME)
    ADD CONSTRAINT CK_PD_STOCK CHECK (STOCK > 0)
    ADD CONSTRAINT CK_PD_STATUS CHECK (PRODUCT_STATUS IN ('Y', 'N'));
    -- 트리거로 인해 STOCK 이 0 아래로 내려가는 것을 방지하기 위한 제약 조건 설정

-- PRODUCT_OPTIONS
ALTER TABLE "PRODUCT_OPTIONS"
    ADD CONSTRAINT "PK_PRODUCT_OPTIONS" PRIMARY KEY ("PRODUCT_OPTIONS_ID")
    ADD CONSTRAINT CK_PDOPT_STATUS CHECK (PRODUCT_OPTIONS_STATUS IN ('Y', 'N'));


-- ORDERS
ALTER TABLE "ORDERS" 
    ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDERS_ID")
    ADD CONSTRAINT CK_ORD_STATUS CHECK (ORDERS_STATUS IN ('Y', 'N'));


-- MEMBERS
ALTER TABLE "MEMBERS" 
    ADD CONSTRAINT "PK_MEMBERS" PRIMARY KEY (MEMBERS_NO)
    ADD CONSTRAINT "UQ_MEM_ID" UNIQUE (MEMBERS_ID)
    ADD CONSTRAINT "UQ_MEM_EMAIL" UNIQUE (MEMBERS_EMAIL)
    ADD CONSTRAINT "UQ_MEM_PHONE" UNIQUE (MEMBERS_PHONE)
    ADD CONSTRAINT "CK_MEM_TYPE" CHECK (MEMBERS_TYPE IN (1, 2))
    ADD CONSTRAINT "CK_MEM_STATUS" CHECK (MEMBERS_STATUS IN ('Y', 'N'));

-- PRODUCT_CART
ALTER TABLE "PRODUCT_CART" ADD CONSTRAINT "PK_PRODUCT_CART" PRIMARY KEY ("PRODUCT_ID", "MEMBERS_NO");

-- QNA
ALTER TABLE "QNA"
    ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("QNA_ID")
    ADD CONSTRAINT CK_QNA_TYPE CHECK (QNA_TYPE IN ('Q', 'A'))
    ADD CONSTRAINT CK_QNA_CONFIDENTIAL CHECK (QNA_CONFIDENTIAL IN ('N', 'Y'))
    ADD CONSTRAINT CK_QNA_STATUS CHECK (QNA_STATUS IN ('Y', 'N'));


-- MEDIA
ALTER TABLE "MEDIA"
    ADD CONSTRAINT "PK_MEDIA" PRIMARY KEY ("MEDIA_ID")
    ADD CONSTRAINT CK_MED_TYPE CHECK (MEDIA_TYPE IN (1, 2))
    ADD CONSTRAINT CK_MED_STATUS CHECK (MEDIA_STATUS IN('Y', 'N'));

-- REPLY
ALTER TABLE "REPLY"
    ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_ID")
    ADD CONSTRAINT CK_REP_STATUS CHECK (REPLY_STATUS IN ('Y', 'N'));

    
-- REVIEW
ALTER TABLE "REVIEW"
    ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_ID")
    ADD CONSTRAINT CK_REV_RATING CHECK (RATING IN (1, 2, 3, 4, 5))
    ADD CONSTRAINT CK_REV_STATUS CHECK (REVIEW_STATUS IN ('Y', 'N'));


-- TAG
ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY ("MEDIA_ID","PRODUCT_ID");

-- SCRAP
ALTER TABLE "SCRAP"
    ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY ("SCRAP_ID")
    ADD CONSTRAINT CK_SCR_STATUS CHECK (SCRAP_STATUS IN ('Y', 'N'));


--외래키 추가 구문
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBERS_TO_BOARD" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE PRODUCT ADD CONSTRAINT "FK_MEMBERS_TO_PRODUCT" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "PRODUCT_OPTIONS" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_OPTIONS" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE "ORDERS" 
    ADD CONSTRAINT "FK_PRODUCT_TO_ORDERS" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_ORDERS" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "PRODUCT_CART" 
    ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_CART" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_PRODUCT_CART" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "QNA" 
    ADD CONSTRAINT "FK_PRODUCT_TO_QNA" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_QNA" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "MEDIA" 
    ADD CONSTRAINT "FK_BOARD_TO_MEDIA" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD"
    ADD CONSTRAINT "FK_MEMBERS_TO_MEDIA" FOREIGN KEY (MEMBERS_NO) REFERENCES MEMBERS
    ADD CONSTRAINT "FK_PRODUCT_TO_MEDIA" FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT;

ALTER TABLE "REPLY" 
    ADD CONSTRAINT "FK_BOARD_TO_REPLY" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_REPLY" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "REVIEW" 
    ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID")
    ADD CONSTRAINT "FK_MEMBERS_TO_REVIEW" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");

ALTER TABLE "TAG" 
    ADD CONSTRAINT "FK_MEDIA_TO_TAG" FOREIGN KEY ("MEDIA_ID") REFERENCES "MEDIA" ("MEDIA_ID")
    ADD CONSTRAINT "FK_PRODUCT_TO_TAG" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_MEMBERS_TO_SCRAP" FOREIGN KEY ("MEMBERS_NO") REFERENCES "MEMBERS" ("MEMBERS_NO");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_BOARD_TO_SCRAP" FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD" ("BOARD_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_MEDIA_TO_SCRAP" FOREIGN KEY ("MEDIA_ID") REFERENCES "MEDIA" ("MEDIA_ID");
ALTER TABLE SCRAP ADD CONSTRAINT "FK_PRODUCT_TO_SCRAP" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");
-- ====================================================================================================================
-- 시퀀스 부분
-- BOARD
DROP SEQUENCE SEQ_BODID;
CREATE SEQUENCE SEQ_BODID NOCACHE;
-- BOARD-MEDIA
DROP SEQUENCE SEQ_MEDID;
CREATE SEQUENCE SEQ_MEDID NOCACHE;
-- MEMBERS
DROP SEQUENCE SEQ_MEMID;
CREATE SEQUENCE SEQ_MEMID NOCACHE;
-- ORDERS
DROP SEQUENCE SEQ_ORDID;
CREATE SEQUENCE SEQ_ORDID NOCACHE;
-- PRODUCT
DROP SEQUENCE SEQ_PDID;
CREATE SEQUENCE SEQ_PDID NOCACHE;
-- PRODUCT_OPTIONS
DROP SEQUENCE SEQ_PDOPTID;
CREATE SEQUENCE SEQ_PDOPTID NOCACHE;
-- QNA
DROP SEQUENCE SEQ_QNAID;
CREATE SEQUENCE SEQ_QNAID NOCACHE;
-- REPLY
DROP SEQUENCE SEQ_REPID;
CREATE SEQUENCE SEQ_REPID NOCACHE;
-- REVIEW
DROP SEQUENCE SEQ_REVID;
CREATE SEQUENCE SEQ_REVID NOCACHE;
-- SCRAP
DROP SEQUENCE SEQ_SCRID;
CREATE SEQUENCE SEQ_SCRID NOCACHE;
-- TAG
DROP SEQUENCE SEQ_TAGID;
CREATE SEQUENCE SEQ_TAGID NOCACHE;
-- =========================================================================================================================
-- 트리거 부분
-- 주문 시 PRODUCT.STOCK(재고량) := PRODUCT.STOCK - ORDERS.ORDERS_AMOUNT값
CREATE OR REPLACE TRIGGER TRG_PRODUCT_AMOUNT
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET STOCK = STOCK - :NEW.ORDERS_AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/
-- 주문 시 PRODUCT.PRODUCT_SALES(누적 판매량) := PRODUCT.PRODUCT_SALES + ORDERS.ORDERS_AMOUNT
CREATE OR REPLACE TRIGGER TRG_PRODUCT_SALES
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET PRODUCT_SALES = PRODUCT_SALES + :NEW.ORDERS_AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/
-- =============================================================================
-- 더미데이터
-- MEMBERS 테이블에 더미 데이터 삽입
INSERT INTO MEMBERS (MEMBERS_NO, MEMBERS_ID, MEMBERS_PWD, MEMBERS_NAME, MEMBERS_BIRTH, MEMBERS_PHONE, MEMBERS_EMAIL, GENDER, MEMBERS_TYPE, COMPANY_NAME, REPRESENTATATIVE, COMPANY_PLACE, COMPANY_PHONE, COMPANY_EMAIL, REG_NUM, MEMBERS_STATUS)
VALUES (SEQ_MEMID.NEXTVAL, 'member1', 'password1', '사용자1', TO_DATE('1990-01-01', 'YYYY-MM-DD'), '010-1111-2222', 'user1@example.com', 'M', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Y');

-- BOARD 테이블에 더미 데이터 삽입
INSERT INTO BOARD (BOARD_ID, BOARD_TITLE, BOARD_VIEWS, BOARD_CREATE_TIME, BOARD_CONTENT, FILTER_TYPE, FILTER_AREA,FILTER_FAMILY, FILTER_WORKER, MEMBERS_NO)
VALUES (SEQ_BODID.NEXTVAL, '게시글 제목 1', 100, SYSDATE, '게시글 내용 1', '주거형태1', 100, '가족형태', '작업자1', 1);

-- PRODUCT 테이블에 더미 데이터 삽입
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_SALES, STOCK, DELIVERY_DATE, PRODUCT_CONTENT, PRODUCT_CREATE_TIME, MEMBERS_NO, PRODUCT_CATEGORY)
VALUES (SEQ_PDID.NEXTVAL, '상품명 1', '10000원', 1000, 500, 3, '상품 내용 1', SYSDATE, 1, 1);

-- PRODUCT_OPTIONS 테이블에 더미 데이터 삽입
INSERT INTO PRODUCT_OPTIONS (PRODUCT_OPTIONS_ID, PRODUCT_OPTIONS_CONTENT, PRODUCT_OPTIONS_PRICE, PRODUCT_OPTIONS_STOCK, PRODUCT_ID)
VALUES (SEQ_PDOPTID.NEXTVAL, '옵션 내용 1', 5000, 100, 1);

-- ORDERS 테이블에 더미 데이터 삽입
INSERT INTO ORDERS (ORDERS_ID, RECIPIENT_NAME, RECIPIENT_PHONE, RECIPIENT_EMAIL, RECIPIENT_ADDRESS, RECIPIENT_POSTCODE, ORDERS_DATE, ORDERS_AMOUNT, PAYMENT_AMOUNT, REQURIEDMENT, PRODUCT_ID, MEMBERS_NO, ORDERS_DELIVERY_STATUS)
VALUES (SEQ_ORDID.NEXTVAL, '수령인1', '010-1234-5678', 'recipient@example.com', '수령인 주소 1', 12345, SYSDATE, 1, 10000, '특별한 요청 없음', 1, 1, '배송준비중');

-- PRODUCT_CART 테이블에 더미 데이터 삽입
INSERT INTO PRODUCT_CART (PRODUCT_ID, MEMBERS_NO, QUANTITY)
VALUES (1, 1, 2);

-- QNA 테이블에 더미 데이터 삽입
INSERT INTO QNA (QNA_ID, QNA_ISSUE_DATE, QNA_CONTENT, QNA_TYPE, QNA_CONFIDENTIAL, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_QNAID.NEXTVAL, SYSDATE, '문의 내용 1', 'Q', 'N', 1, 1);

-- MEDIA 테이블에 더미 데이터 삽입
INSERT INTO MEDIA (MEDIA_ID, BOARD_ID, MEDIA_TYPE, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, FILE_LEVEL)
VALUES (SEQ_MEDID.NEXTVAL, 1, 1, '원본명', '수정명', '미디어 주소 1', 1);

-- REPLY 테이블에 더미 데이터 삽입
INSERT INTO REPLY (REPLY_ID, REPLY_TEXT, REPLY_CREATE_DATE, BOARD_ID, MEMBERS_NO)
VALUES (SEQ_REPID.NEXTVAL, '댓글 내용 1', SYSDATE, 1, 1);

-- REVIEW 테이블에 더미 데이터 삽입
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_IMG, REVIEW_DETAIL, HELPFUL, REVIEW_CREATE_DAY, PRODUCT_ID, MEMBERS_NO)
VALUES (SEQ_REVID.NEXTVAL, 5, '리뷰 이미지 주소 1', '리뷰 내용 1', '도움이 됨', SYSDATE, 1, 1);

-- TAG 테이블에 더미 데이터 삽입
INSERT INTO TAG (MEDIA_ID, PRODUCT_ID, TAG_X, TAG_Y)
VALUES (1, 1, 100, 200);

-- SCRAP 테이블에 더미 데이터 삽입
INSERT INTO SCRAP (SCRAP_ID, SCRAP_TYPE, MEMBERS_NO, BOARD_ID, MEDIA_ID, PRODUCT_ID, SCRAP_CREATE_TIME, SCRAP_MODIFY_TIME)
VALUES (SEQ_SCRID.NEXTVAL, 1, 1, 1, 1, 1, SYSDATE, SYSDATE);